// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentNameExists = `-- name: AgentNameExists :one
SELECT EXISTS(
    SELECT 1 FROM agents
    WHERE space_id = $1 AND name_key = $2
)
`

type AgentNameExistsParams struct {
	SpaceID string
	NameKey string
}

func (q *Queries) AgentNameExists(ctx context.Context, arg AgentNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentNameExists, arg.SpaceID, arg.NameKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (
    agent_id, space_id, machine_id, owner_user_id,
    adapter_key, occurrence_key, name, name_key
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING agent_id, space_id, machine_id, owner_user_id, adapter_key, occurrence_key, name, name_key, created_at, removed_at
`

type InsertAgentParams struct {
	AgentID       string
	SpaceID       string
	MachineID     string
	OwnerUserID   string
	AdapterKey    string
	OccurrenceKey string
	Name          string
	NameKey       string
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.AgentID,
		arg.SpaceID,
		arg.MachineID,
		arg.OwnerUserID,
		arg.AdapterKey,
		arg.OccurrenceKey,
		arg.Name,
		arg.NameKey,
	)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.SpaceID,
		&i.MachineID,
		&i.OwnerUserID,
		&i.AdapterKey,
		&i.OccurrenceKey,
		&i.Name,
		&i.NameKey,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const insertAgentPresence = `-- name: InsertAgentPresence :exec
INSERT INTO agent_presence (agent_id, present)
VALUES ($1, false)
`

func (q *Queries) InsertAgentPresence(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, insertAgentPresence, agentID)
	return err
}

const listInventoryAgents = `-- name: ListInventoryAgents :many
SELECT agent.agent_id, agent.machine_id, agent.name, agent.owner_user_id,
    owner.display_name AS owner_name, agent.removed_at,
    presence.last_present_at,
    (agent.removed_at IS NULL
        AND machine.revoked_at IS NULL
        AND presence.present
        AND machine.agent_reported_at > transaction_timestamp()
            - make_interval(secs => $1::int)) AS online
FROM agents AS agent
INNER JOIN agent_presence AS presence ON presence.agent_id = agent.agent_id
INNER JOIN machines AS machine ON machine.machine_id = agent.machine_id
INNER JOIN carry_users AS owner ON owner.user_id = agent.owner_user_id
WHERE agent.machine_id = ANY($2::uuid[])
ORDER BY agent.machine_id, agent.agent_id
`

type ListInventoryAgentsParams struct {
	FreshnessSeconds int32
	MachineIds       []string
}

type ListInventoryAgentsRow struct {
	AgentID       string
	MachineID     string
	Name          string
	OwnerUserID   string
	OwnerName     string
	RemovedAt     pgtype.Timestamptz
	LastPresentAt pgtype.Timestamptz
	Online        *bool
}

func (q *Queries) ListInventoryAgents(ctx context.Context, arg ListInventoryAgentsParams) ([]ListInventoryAgentsRow, error) {
	rows, err := q.db.Query(ctx, listInventoryAgents, arg.FreshnessSeconds, arg.MachineIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryAgentsRow
	for rows.Next() {
		var i ListInventoryAgentsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.MachineID,
			&i.Name,
			&i.OwnerUserID,
			&i.OwnerName,
			&i.RemovedAt,
			&i.LastPresentAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineAgentBindings = `-- name: ListMachineAgentBindings :many
SELECT adapter_key, occurrence_key
FROM agents
WHERE machine_id = $1
`

type ListMachineAgentBindingsRow struct {
	AdapterKey    string
	OccurrenceKey string
}

func (q *Queries) ListMachineAgentBindings(ctx context.Context, machineID string) ([]ListMachineAgentBindingsRow, error) {
	rows, err := q.db.Query(ctx, listMachineAgentBindings, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachineAgentBindingsRow
	for rows.Next() {
		var i ListMachineAgentBindingsRow
		if err := rows.Scan(&i.AdapterKey, &i.OccurrenceKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAgentReportMachine = `-- name: LoadAgentReportMachine :one
SELECT machine_id, space_id, enrolled_by_user_id
FROM machines
WHERE machine_id = $1
`

type LoadAgentReportMachineRow struct {
	MachineID        string
	SpaceID          string
	EnrolledByUserID string
}

func (q *Queries) LoadAgentReportMachine(ctx context.Context, machineID string) (LoadAgentReportMachineRow, error) {
	row := q.db.QueryRow(ctx, loadAgentReportMachine, machineID)
	var i LoadAgentReportMachineRow
	err := row.Scan(&i.MachineID, &i.SpaceID, &i.EnrolledByUserID)
	return i, err
}

const lockActiveAgentsForMachineRemoval = `-- name: LockActiveAgentsForMachineRemoval :many
SELECT agent_id
FROM agents
WHERE machine_id = $1 AND removed_at IS NULL
ORDER BY agent_id
FOR UPDATE
`

func (q *Queries) LockActiveAgentsForMachineRemoval(ctx context.Context, machineID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockActiveAgentsForMachineRemoval, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var agent_id string
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveAgentsForOwnerRemoval = `-- name: LockActiveAgentsForOwnerRemoval :many
SELECT agent_id
FROM agents
WHERE space_id = $1
    AND owner_user_id = $2
    AND removed_at IS NULL
ORDER BY agent_id
FOR UPDATE
`

type LockActiveAgentsForOwnerRemovalParams struct {
	SpaceID     string
	OwnerUserID string
}

func (q *Queries) LockActiveAgentsForOwnerRemoval(ctx context.Context, arg LockActiveAgentsForOwnerRemovalParams) ([]string, error) {
	rows, err := q.db.Query(ctx, lockActiveAgentsForOwnerRemoval, arg.SpaceID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var agent_id string
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentApproverMembership = `-- name: LockAgentApproverMembership :one
SELECT user_id, revoked_at
FROM space_memberships
WHERE space_id = $1 AND user_id = $2
FOR UPDATE
`

type LockAgentApproverMembershipParams struct {
	SpaceID string
	UserID  string
}

type LockAgentApproverMembershipRow struct {
	UserID    string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) LockAgentApproverMembership(ctx context.Context, arg LockAgentApproverMembershipParams) (LockAgentApproverMembershipRow, error) {
	row := q.db.QueryRow(ctx, lockAgentApproverMembership, arg.SpaceID, arg.UserID)
	var i LockAgentApproverMembershipRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const lockAgentsForMachine = `-- name: LockAgentsForMachine :many
SELECT agent.agent_id, agent.space_id, agent.machine_id, agent.owner_user_id,
    agent.adapter_key, agent.occurrence_key, agent.name, agent.name_key,
    agent.created_at, agent.removed_at,
    presence.present, presence.last_present_at
FROM agents AS agent
INNER JOIN agent_presence AS presence ON presence.agent_id = agent.agent_id
WHERE agent.machine_id = $1
ORDER BY agent.agent_id
FOR UPDATE OF agent
`

type LockAgentsForMachineRow struct {
	AgentID       string
	SpaceID       string
	MachineID     string
	OwnerUserID   string
	AdapterKey    string
	OccurrenceKey string
	Name          string
	NameKey       string
	CreatedAt     pgtype.Timestamptz
	RemovedAt     pgtype.Timestamptz
	Present       bool
	LastPresentAt pgtype.Timestamptz
}

func (q *Queries) LockAgentsForMachine(ctx context.Context, machineID string) ([]LockAgentsForMachineRow, error) {
	rows, err := q.db.Query(ctx, lockAgentsForMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAgentsForMachineRow
	for rows.Next() {
		var i LockAgentsForMachineRow
		if err := rows.Scan(
			&i.AgentID,
			&i.SpaceID,
			&i.MachineID,
			&i.OwnerUserID,
			&i.AdapterKey,
			&i.OccurrenceKey,
			&i.Name,
			&i.NameKey,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.Present,
			&i.LastPresentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMachineForAgentReport = `-- name: LockMachineForAgentReport :one
SELECT machine_id, space_id, display_name, public_key_der, certificate_pem, certificate_serial, enrolled_by_user_id, enrolled_at, revoked_at, revocation_actor_kind, revoked_by_user_id, revocation_idempotency_key, revocation_request_digest, agent_report_revision, agent_reported_at, last_agent_report_id, last_agent_report_digest, last_agent_report_unsupported_keys, last_agent_report_setup_required_keys
FROM machines
WHERE machine_id = $1
FOR UPDATE
`

func (q *Queries) LockMachineForAgentReport(ctx context.Context, machineID string) (Machine, error) {
	row := q.db.QueryRow(ctx, lockMachineForAgentReport, machineID)
	var i Machine
	err := row.Scan(
		&i.MachineID,
		&i.SpaceID,
		&i.DisplayName,
		&i.PublicKeyDer,
		&i.CertificatePem,
		&i.CertificateSerial,
		&i.EnrolledByUserID,
		&i.EnrolledAt,
		&i.RevokedAt,
		&i.RevocationActorKind,
		&i.RevokedByUserID,
		&i.RevocationIdempotencyKey,
		&i.RevocationRequestDigest,
		&i.AgentReportRevision,
		&i.AgentReportedAt,
		&i.LastAgentReportID,
		&i.LastAgentReportDigest,
		&i.LastAgentReportUnsupportedKeys,
		&i.LastAgentReportSetupRequiredKeys,
	)
	return i, err
}

const lockSpaceForAgentAllocation = `-- name: LockSpaceForAgentAllocation :one
SELECT space_id
FROM spaces
WHERE space_id = $1
FOR NO KEY UPDATE
`

func (q *Queries) LockSpaceForAgentAllocation(ctx context.Context, spaceID string) (string, error) {
	row := q.db.QueryRow(ctx, lockSpaceForAgentAllocation, spaceID)
	var space_id string
	err := row.Scan(&space_id)
	return space_id, err
}

const removeActiveAgentsForMachine = `-- name: RemoveActiveAgentsForMachine :exec
WITH removed AS (
    UPDATE agents
    SET removed_at = transaction_timestamp()
    WHERE machine_id = $1 AND removed_at IS NULL
    RETURNING agent_id
)
UPDATE agent_presence AS presence
SET present = false
FROM removed
WHERE presence.agent_id = removed.agent_id
`

func (q *Queries) RemoveActiveAgentsForMachine(ctx context.Context, machineID string) error {
	_, err := q.db.Exec(ctx, removeActiveAgentsForMachine, machineID)
	return err
}

const removeActiveAgentsForOwner = `-- name: RemoveActiveAgentsForOwner :exec
WITH removed AS (
    UPDATE agents
    SET removed_at = transaction_timestamp()
    WHERE space_id = $1
        AND owner_user_id = $2
        AND removed_at IS NULL
    RETURNING agent_id
)
UPDATE agent_presence AS presence
SET present = false
FROM removed
WHERE presence.agent_id = removed.agent_id
`

type RemoveActiveAgentsForOwnerParams struct {
	SpaceID     string
	OwnerUserID string
}

func (q *Queries) RemoveActiveAgentsForOwner(ctx context.Context, arg RemoveActiveAgentsForOwnerParams) error {
	_, err := q.db.Exec(ctx, removeActiveAgentsForOwner, arg.SpaceID, arg.OwnerUserID)
	return err
}

const setActiveAgentPresent = `-- name: SetActiveAgentPresent :execrows
UPDATE agent_presence AS presence
SET present = true, last_present_at = transaction_timestamp()
FROM agents AS agent
WHERE presence.agent_id = agent.agent_id
    AND agent.agent_id = $1
    AND agent.removed_at IS NULL
`

func (q *Queries) SetActiveAgentPresent(ctx context.Context, agentID string) (int64, error) {
	result, err := q.db.Exec(ctx, setActiveAgentPresent, agentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMachineActiveAgentsAbsent = `-- name: SetMachineActiveAgentsAbsent :exec
UPDATE agent_presence AS presence
SET present = false
FROM agents AS agent
WHERE presence.agent_id = agent.agent_id
    AND agent.machine_id = $1
    AND agent.removed_at IS NULL
`

func (q *Queries) SetMachineActiveAgentsAbsent(ctx context.Context, machineID string) error {
	_, err := q.db.Exec(ctx, setMachineActiveAgentsAbsent, machineID)
	return err
}

const updateMachineAgentReport = `-- name: UpdateMachineAgentReport :one
UPDATE machines
SET agent_report_revision = agent_report_revision + 1,
    agent_reported_at = transaction_timestamp(),
    last_agent_report_id = $1,
    last_agent_report_digest = $2,
    last_agent_report_unsupported_keys = $3::text[],
    last_agent_report_setup_required_keys = $4::text[]
WHERE machine_id = $5
RETURNING agent_report_revision
`

type UpdateMachineAgentReportParams struct {
	ReportID          pgtype.UUID
	ReportDigest      []byte
	UnsupportedKeys   []string
	SetupRequiredKeys []string
	MachineID         string
}

func (q *Queries) UpdateMachineAgentReport(ctx context.Context, arg UpdateMachineAgentReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateMachineAgentReport,
		arg.ReportID,
		arg.ReportDigest,
		arg.UnsupportedKeys,
		arg.SetupRequiredKeys,
		arg.MachineID,
	)
	var agent_report_revision int64
	err := row.Scan(&agent_report_revision)
	return agent_report_revision, err
}
