// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateUserToken = `-- name: AuthenticateUserToken :one
SELECT
    token.user_id,
    carry_user.display_name
FROM user_tokens AS token
INNER JOIN carry_users AS carry_user ON token.user_id = carry_user.user_id
WHERE
    token.token_hash = $1
    AND token.revoked_at IS null
    AND token.expires_at > transaction_timestamp()
`

type AuthenticateUserTokenRow struct {
	UserID      string
	DisplayName string
}

func (q *Queries) AuthenticateUserToken(ctx context.Context, tokenHash []byte) (AuthenticateUserTokenRow, error) {
	row := q.db.QueryRow(ctx, authenticateUserToken, tokenHash)
	var i AuthenticateUserTokenRow
	err := row.Scan(&i.UserID, &i.DisplayName)
	return i, err
}

const createBootstrapMembership = `-- name: CreateBootstrapMembership :exec
INSERT INTO space_memberships (space_id, user_id, can_enroll_machines)
VALUES ($1, $2, true)
`

type CreateBootstrapMembershipParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) CreateBootstrapMembership(ctx context.Context, arg CreateBootstrapMembershipParams) error {
	_, err := q.db.Exec(ctx, createBootstrapMembership, arg.SpaceID, arg.UserID)
	return err
}

const createBootstrapSpace = `-- name: CreateBootstrapSpace :exec
INSERT INTO spaces (space_id, name)
VALUES ($1, $2)
`

type CreateBootstrapSpaceParams struct {
	SpaceID string
	Name    string
}

func (q *Queries) CreateBootstrapSpace(ctx context.Context, arg CreateBootstrapSpaceParams) error {
	_, err := q.db.Exec(ctx, createBootstrapSpace, arg.SpaceID, arg.Name)
	return err
}

const createBootstrapUser = `-- name: CreateBootstrapUser :exec
INSERT INTO carry_users (user_id, display_name)
VALUES ($1, $2)
`

type CreateBootstrapUserParams struct {
	UserID      string
	DisplayName string
}

func (q *Queries) CreateBootstrapUser(ctx context.Context, arg CreateBootstrapUserParams) error {
	_, err := q.db.Exec(ctx, createBootstrapUser, arg.UserID, arg.DisplayName)
	return err
}

const createUserToken = `-- name: CreateUserToken :exec
INSERT INTO user_tokens (token_id, user_id, token_hash, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateUserTokenParams struct {
	TokenID   string
	UserID    string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) error {
	_, err := q.db.Exec(ctx, createUserToken,
		arg.TokenID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const isBootstrapped = `-- name: IsBootstrapped :one
SELECT exists(SELECT 1 FROM spaces)
`

func (q *Queries) IsBootstrapped(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isBootstrapped)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loadPreparedBootstrap = `-- name: LoadPreparedBootstrap :one
SELECT
    carry_user.display_name,
    space.name AS space_name,
    membership.can_enroll_machines,
    user_token.token_hash,
    user_token.expires_at
FROM carry_users AS carry_user
INNER JOIN
    space_memberships AS membership
    ON carry_user.user_id = membership.user_id
INNER JOIN spaces AS space ON membership.space_id = space.space_id
INNER JOIN user_tokens AS user_token ON carry_user.user_id = user_token.user_id
WHERE
    carry_user.user_id = $1
    AND space.space_id = $2
    AND user_token.token_id = $3
`

type LoadPreparedBootstrapParams struct {
	UserID  string
	SpaceID string
	TokenID string
}

type LoadPreparedBootstrapRow struct {
	DisplayName       string
	SpaceName         string
	CanEnrollMachines bool
	TokenHash         []byte
	ExpiresAt         pgtype.Timestamptz
}

func (q *Queries) LoadPreparedBootstrap(ctx context.Context, arg LoadPreparedBootstrapParams) (LoadPreparedBootstrapRow, error) {
	row := q.db.QueryRow(ctx, loadPreparedBootstrap, arg.UserID, arg.SpaceID, arg.TokenID)
	var i LoadPreparedBootstrapRow
	err := row.Scan(
		&i.DisplayName,
		&i.SpaceName,
		&i.CanEnrollMachines,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const lockBootstrap = `-- name: LockBootstrap :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) LockBootstrap(ctx context.Context, lockID int64) error {
	_, err := q.db.Exec(ctx, lockBootstrap, lockID)
	return err
}
