// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browser_session.sql

package dbsqlc

import (
	"context"
)

const authenticateBrowserSession = `-- name: AuthenticateBrowserSession :one
SELECT
    browser_session.user_id,
    carry_user.display_name
FROM browser_sessions AS browser_session
INNER JOIN
    carry_users AS carry_user
    ON browser_session.user_id = carry_user.user_id
WHERE
    browser_session.session_id = $1
    AND browser_session.revoked_at IS NULL
    AND browser_session.expires_at > transaction_timestamp()
`

type AuthenticateBrowserSessionRow struct {
	UserID      string
	DisplayName *string
}

func (q *Queries) AuthenticateBrowserSession(ctx context.Context, sessionID string) (AuthenticateBrowserSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateBrowserSession, sessionID)
	var i AuthenticateBrowserSessionRow
	err := row.Scan(&i.UserID, &i.DisplayName)
	return i, err
}

const revokeBrowserSession = `-- name: RevokeBrowserSession :execrows
UPDATE browser_sessions
SET revoked_at = transaction_timestamp()
WHERE session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeBrowserSession(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeBrowserSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
