// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browser_session.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateBrowserSession = `-- name: AuthenticateBrowserSession :one
SELECT
    browser_session.user_id,
    carry_user.display_name
FROM browser_sessions AS browser_session
INNER JOIN
    carry_users AS carry_user
    ON browser_session.user_id = carry_user.user_id
WHERE
    browser_session.session_id = $1
    AND browser_session.revoked_at IS NULL
    AND browser_session.expires_at > transaction_timestamp()
`

type AuthenticateBrowserSessionRow struct {
	UserID      string
	DisplayName string
}

func (q *Queries) AuthenticateBrowserSession(ctx context.Context, sessionID string) (AuthenticateBrowserSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateBrowserSession, sessionID)
	var i AuthenticateBrowserSessionRow
	err := row.Scan(&i.UserID, &i.DisplayName)
	return i, err
}

const createBrowserSession = `-- name: CreateBrowserSession :one
INSERT INTO browser_sessions (session_id, user_id, identity_proof_method, expires_at)
VALUES (
    $1,
    $2,
    $3,
    transaction_timestamp() + interval '30 days'
)
RETURNING user_id, created_at, expires_at, revoked_at, session_id, identity_proved_at, identity_proof_method
`

type CreateBrowserSessionParams struct {
	SessionID           string
	UserID              string
	IdentityProofMethod string
}

func (q *Queries) CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) (BrowserSession, error) {
	row := q.db.QueryRow(ctx, createBrowserSession, arg.SessionID, arg.UserID, arg.IdentityProofMethod)
	var i BrowserSession
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.SessionID,
		&i.IdentityProvedAt,
		&i.IdentityProofMethod,
	)
	return i, err
}

const loadActiveBrowserSessionByID = `-- name: LoadActiveBrowserSessionByID :one
SELECT session_id, user_id, expires_at, revoked_at, identity_proved_at, identity_proof_method
FROM browser_sessions
WHERE session_id = $1
    AND revoked_at IS NULL
    AND expires_at > transaction_timestamp()
`

type LoadActiveBrowserSessionByIDRow struct {
	SessionID           string
	UserID              string
	ExpiresAt           pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
	IdentityProvedAt    pgtype.Timestamptz
	IdentityProofMethod string
}

func (q *Queries) LoadActiveBrowserSessionByID(ctx context.Context, sessionID string) (LoadActiveBrowserSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, loadActiveBrowserSessionByID, sessionID)
	var i LoadActiveBrowserSessionByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IdentityProvedAt,
		&i.IdentityProofMethod,
	)
	return i, err
}

const loadBrowserSessionByID = `-- name: LoadBrowserSessionByID :one
SELECT session_id, user_id, expires_at, revoked_at, identity_proved_at, identity_proof_method
FROM browser_sessions
WHERE session_id = $1
`

type LoadBrowserSessionByIDRow struct {
	SessionID           string
	UserID              string
	ExpiresAt           pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
	IdentityProvedAt    pgtype.Timestamptz
	IdentityProofMethod string
}

func (q *Queries) LoadBrowserSessionByID(ctx context.Context, sessionID string) (LoadBrowserSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, loadBrowserSessionByID, sessionID)
	var i LoadBrowserSessionByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IdentityProvedAt,
		&i.IdentityProofMethod,
	)
	return i, err
}

const revokeBrowserSession = `-- name: RevokeBrowserSession :execrows
UPDATE browser_sessions
SET revoked_at = transaction_timestamp()
WHERE session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeBrowserSession(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeBrowserSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
