// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cli_login.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveCLILogin = `-- name: ApproveCLILogin :one
UPDATE cli_login_requests
SET approved_at = transaction_timestamp(),
    approved_by_user_id = $1,
    approved_space_id = $2,
    approval_idempotency_key = $3,
    approval_request_digest = $4,
    prepared_credential_id = $5,
    proposed_replacement_credential_id = $6
WHERE request_id = $7
    AND approved_at IS NULL AND denied_at IS NULL AND cancelled_at IS NULL
    AND redeemed_at IS NULL AND expires_at > transaction_timestamp()
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

type ApproveCLILoginParams struct {
	UserID                  pgtype.UUID
	SpaceID                 pgtype.UUID
	IdempotencyKey          *string
	RequestDigest           []byte
	CredentialID            pgtype.UUID
	ReplacementCredentialID pgtype.UUID
	RequestID               string
}

func (q *Queries) ApproveCLILogin(ctx context.Context, arg ApproveCLILoginParams) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, approveCLILogin,
		arg.UserID,
		arg.SpaceID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.CredentialID,
		arg.ReplacementCredentialID,
		arg.RequestID,
	)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const authenticateCLICredential = `-- name: AuthenticateCLICredential :one
SELECT credential.user_id, carry_user.display_name AS display_name
FROM cli_credentials AS credential
INNER JOIN carry_users AS carry_user ON carry_user.user_id = credential.user_id
WHERE credential.credential_id = $1
    AND credential.revoked_at IS NULL AND credential.expires_at > transaction_timestamp()
`

type AuthenticateCLICredentialRow struct {
	UserID      string
	DisplayName string
}

func (q *Queries) AuthenticateCLICredential(ctx context.Context, credentialID string) (AuthenticateCLICredentialRow, error) {
	row := q.db.QueryRow(ctx, authenticateCLICredential, credentialID)
	var i AuthenticateCLICredentialRow
	err := row.Scan(&i.UserID, &i.DisplayName)
	return i, err
}

const cLIDatabaseTime = `-- name: CLIDatabaseTime :one
SELECT transaction_timestamp()::timestamptz
`

func (q *Queries) CLIDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, cLIDatabaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const cancelCLILogin = `-- name: CancelCLILogin :one
UPDATE cli_login_requests
SET cancelled_at = transaction_timestamp()
WHERE request_id = $1
    AND denied_at IS NULL AND cancelled_at IS NULL AND redeemed_at IS NULL
    AND expires_at > transaction_timestamp()
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

func (q *Queries) CancelCLILogin(ctx context.Context, requestID string) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, cancelCLILogin, requestID)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const countLiveCLILogins = `-- name: CountLiveCLILogins :one
SELECT count(*) FROM cli_login_requests
WHERE expires_at > transaction_timestamp()
    AND denied_at IS NULL AND cancelled_at IS NULL AND redeemed_at IS NULL
`

func (q *Queries) CountLiveCLILogins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveCLILogins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveCLILoginsForSource = `-- name: CountLiveCLILoginsForSource :one
SELECT count(*) FROM cli_login_requests
WHERE source_digest = $1
    AND expires_at > transaction_timestamp()
    AND denied_at IS NULL AND cancelled_at IS NULL AND redeemed_at IS NULL
`

func (q *Queries) CountLiveCLILoginsForSource(ctx context.Context, sourceDigest []byte) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveCLILoginsForSource, sourceDigest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentCLILookupFailuresForSession = `-- name: CountRecentCLILookupFailuresForSession :one
SELECT count(*) FROM cli_login_lookup_failures
WHERE browser_session_id = $1
    AND created_at > transaction_timestamp() - interval '10 minutes'
`

func (q *Queries) CountRecentCLILookupFailuresForSession(ctx context.Context, browserSessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentCLILookupFailuresForSession, browserSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentCLILookupFailuresForSource = `-- name: CountRecentCLILookupFailuresForSource :one
SELECT count(*) FROM cli_login_lookup_failures
WHERE source_digest = $1
    AND created_at > transaction_timestamp() - interval '10 minutes'
`

func (q *Queries) CountRecentCLILookupFailuresForSource(ctx context.Context, sourceDigest []byte) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentCLILookupFailuresForSource, sourceDigest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCLICredential = `-- name: CreateCLICredential :one
INSERT INTO cli_credentials (credential_id, login_request_id, user_id, label)
VALUES ($1, $2, $3, $4)
RETURNING credential_id, login_request_id, user_id, label, created_at, expires_at, revoked_at, revoked_by_user_id, revocation_idempotency_key, revocation_request_digest
`

type CreateCLICredentialParams struct {
	CredentialID   string
	LoginRequestID string
	UserID         string
	Label          string
}

func (q *Queries) CreateCLICredential(ctx context.Context, arg CreateCLICredentialParams) (CliCredential, error) {
	row := q.db.QueryRow(ctx, createCLICredential,
		arg.CredentialID,
		arg.LoginRequestID,
		arg.UserID,
		arg.Label,
	)
	var i CliCredential
	err := row.Scan(
		&i.CredentialID,
		&i.LoginRequestID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevocationIdempotencyKey,
		&i.RevocationRequestDigest,
	)
	return i, err
}

const createCLILogin = `-- name: CreateCLILogin :one
INSERT INTO cli_login_requests (
    request_id, begin_idempotency_key, begin_request_digest, user_code_digest,
    code_generation, source_digest, label, proposed_replacement_credential_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

type CreateCLILoginParams struct {
	RequestID                       string
	BeginIdempotencyKey             string
	BeginRequestDigest              []byte
	UserCodeDigest                  []byte
	CodeGeneration                  int16
	SourceDigest                    []byte
	Label                           string
	ProposedReplacementCredentialID pgtype.UUID
}

func (q *Queries) CreateCLILogin(ctx context.Context, arg CreateCLILoginParams) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, createCLILogin,
		arg.RequestID,
		arg.BeginIdempotencyKey,
		arg.BeginRequestDigest,
		arg.UserCodeDigest,
		arg.CodeGeneration,
		arg.SourceDigest,
		arg.Label,
		arg.ProposedReplacementCredentialID,
	)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const denyCLILogin = `-- name: DenyCLILogin :one
UPDATE cli_login_requests
SET denied_at = transaction_timestamp(), denied_by_user_id = $1,
    denial_idempotency_key = $2,
    denial_request_digest = $3
WHERE request_id = $4
    AND approved_at IS NULL AND denied_at IS NULL AND cancelled_at IS NULL
    AND redeemed_at IS NULL AND expires_at > transaction_timestamp()
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

type DenyCLILoginParams struct {
	UserID         pgtype.UUID
	IdempotencyKey *string
	RequestDigest  []byte
	RequestID      string
}

func (q *Queries) DenyCLILogin(ctx context.Context, arg DenyCLILoginParams) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, denyCLILogin,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.RequestID,
	)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const findLiveCLILoginByCode = `-- name: FindLiveCLILoginByCode :one
SELECT request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until FROM cli_login_requests
WHERE user_code_digest = $1
    AND expires_at > transaction_timestamp()
    AND denied_at IS NULL AND cancelled_at IS NULL
`

func (q *Queries) FindLiveCLILoginByCode(ctx context.Context, userCodeDigest []byte) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, findLiveCLILoginByCode, userCodeDigest)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const listActiveCLICredentials = `-- name: ListActiveCLICredentials :many
SELECT credential.credential_id, credential.label, credential.created_at, credential.expires_at,
    request.approved_space_id, coalesce(space.name, '') AS approved_space_name
FROM cli_credentials AS credential
INNER JOIN cli_login_requests AS request ON request.request_id = credential.login_request_id
LEFT JOIN space_memberships AS membership
    ON membership.space_id = request.approved_space_id
    AND membership.user_id = credential.user_id
    AND membership.revoked_at IS NULL
LEFT JOIN spaces AS space
    ON space.space_id = membership.space_id
WHERE credential.user_id = $1
    AND credential.revoked_at IS NULL AND credential.expires_at > transaction_timestamp()
ORDER BY credential.created_at DESC, credential.credential_id
`

type ListActiveCLICredentialsRow struct {
	CredentialID      string
	Label             string
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	ApprovedSpaceID   pgtype.UUID
	ApprovedSpaceName string
}

func (q *Queries) ListActiveCLICredentials(ctx context.Context, userID string) ([]ListActiveCLICredentialsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCLICredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCLICredentialsRow
	for rows.Next() {
		var i ListActiveCLICredentialsRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.Label,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ApprovedSpaceID,
			&i.ApprovedSpaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadCLICredential = `-- name: LoadCLICredential :one
SELECT credential_id, login_request_id, user_id, label, created_at, expires_at, revoked_at, revoked_by_user_id, revocation_idempotency_key, revocation_request_digest FROM cli_credentials WHERE credential_id = $1
`

func (q *Queries) LoadCLICredential(ctx context.Context, credentialID string) (CliCredential, error) {
	row := q.db.QueryRow(ctx, loadCLICredential, credentialID)
	var i CliCredential
	err := row.Scan(
		&i.CredentialID,
		&i.LoginRequestID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevocationIdempotencyKey,
		&i.RevocationRequestDigest,
	)
	return i, err
}

const loadCLICredentialForUser = `-- name: LoadCLICredentialForUser :one
SELECT credential_id, login_request_id, user_id, label, created_at, expires_at, revoked_at, revoked_by_user_id, revocation_idempotency_key, revocation_request_digest FROM cli_credentials
WHERE credential_id = $1 AND user_id = $2
`

type LoadCLICredentialForUserParams struct {
	CredentialID string
	UserID       string
}

func (q *Queries) LoadCLICredentialForUser(ctx context.Context, arg LoadCLICredentialForUserParams) (CliCredential, error) {
	row := q.db.QueryRow(ctx, loadCLICredentialForUser, arg.CredentialID, arg.UserID)
	var i CliCredential
	err := row.Scan(
		&i.CredentialID,
		&i.LoginRequestID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevocationIdempotencyKey,
		&i.RevocationRequestDigest,
	)
	return i, err
}

const loadCLILoginForBegin = `-- name: LoadCLILoginForBegin :one
SELECT request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until FROM cli_login_requests WHERE request_id = $1
`

func (q *Queries) LoadCLILoginForBegin(ctx context.Context, requestID string) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, loadCLILoginForBegin, requestID)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const lockActiveMembershipForCLILogin = `-- name: LockActiveMembershipForCLILogin :one
SELECT user_id FROM space_memberships
WHERE space_id = $1 AND user_id = $2 AND revoked_at IS NULL
FOR UPDATE
`

type LockActiveMembershipForCLILoginParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) LockActiveMembershipForCLILogin(ctx context.Context, arg LockActiveMembershipForCLILoginParams) (string, error) {
	row := q.db.QueryRow(ctx, lockActiveMembershipForCLILogin, arg.SpaceID, arg.UserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const lockBrowserSessionForCLILogin = `-- name: LockBrowserSessionForCLILogin :one
SELECT session.user_id, carry_user.display_name AS display_name
FROM browser_sessions AS session
INNER JOIN carry_users AS carry_user ON carry_user.user_id = session.user_id
WHERE session.session_id = $1
    AND session.revoked_at IS NULL
    AND session.expires_at > transaction_timestamp()
FOR UPDATE OF session
`

type LockBrowserSessionForCLILoginRow struct {
	UserID      string
	DisplayName string
}

func (q *Queries) LockBrowserSessionForCLILogin(ctx context.Context, sessionID string) (LockBrowserSessionForCLILoginRow, error) {
	row := q.db.QueryRow(ctx, lockBrowserSessionForCLILogin, sessionID)
	var i LockBrowserSessionForCLILoginRow
	err := row.Scan(&i.UserID, &i.DisplayName)
	return i, err
}

const lockCLICredential = `-- name: LockCLICredential :one
SELECT credential_id, login_request_id, user_id, label, created_at, expires_at, revoked_at, revoked_by_user_id, revocation_idempotency_key, revocation_request_digest FROM cli_credentials WHERE credential_id = $1 FOR UPDATE
`

func (q *Queries) LockCLICredential(ctx context.Context, credentialID string) (CliCredential, error) {
	row := q.db.QueryRow(ctx, lockCLICredential, credentialID)
	var i CliCredential
	err := row.Scan(
		&i.CredentialID,
		&i.LoginRequestID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevocationIdempotencyKey,
		&i.RevocationRequestDigest,
	)
	return i, err
}

const lockCLILoginAdmission = `-- name: LockCLILoginAdmission :exec
SELECT pg_advisory_xact_lock(551917301::bigint)
`

func (q *Queries) LockCLILoginAdmission(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCLILoginAdmission)
	return err
}

const lockCLILoginLookupBudget = `-- name: LockCLILoginLookupBudget :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 11471))
`

func (q *Queries) LockCLILoginLookupBudget(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, lockCLILoginLookupBudget, lockKey)
	return err
}

const lockCLILoginRequest = `-- name: LockCLILoginRequest :one
SELECT request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until FROM cli_login_requests
WHERE request_id = $1
FOR UPDATE
`

func (q *Queries) LockCLILoginRequest(ctx context.Context, requestID string) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, lockCLILoginRequest, requestID)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const lockSpaceForCLILogin = `-- name: LockSpaceForCLILogin :one
SELECT space_id FROM spaces WHERE space_id = $1 FOR KEY SHARE
`

func (q *Queries) LockSpaceForCLILogin(ctx context.Context, spaceID string) (string, error) {
	row := q.db.QueryRow(ctx, lockSpaceForCLILogin, spaceID)
	var space_id string
	err := row.Scan(&space_id)
	return space_id, err
}

const recordCLILoginLookupFailure = `-- name: RecordCLILoginLookupFailure :exec
INSERT INTO cli_login_lookup_failures (failure_id, browser_session_id, source_digest)
VALUES ($1, $2, $3)
`

type RecordCLILoginLookupFailureParams struct {
	FailureID        string
	BrowserSessionID string
	SourceDigest     []byte
}

func (q *Queries) RecordCLILoginLookupFailure(ctx context.Context, arg RecordCLILoginLookupFailureParams) error {
	_, err := q.db.Exec(ctx, recordCLILoginLookupFailure, arg.FailureID, arg.BrowserSessionID, arg.SourceDigest)
	return err
}

const recordCLILoginPoll = `-- name: RecordCLILoginPoll :one
UPDATE cli_login_requests
SET last_polled_at = transaction_timestamp()
WHERE request_id = $1
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

func (q *Queries) RecordCLILoginPoll(ctx context.Context, requestID string) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, recordCLILoginPoll, requestID)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const redeemCLILogin = `-- name: RedeemCLILogin :one
UPDATE cli_login_requests
SET resulting_credential_id = $1,
    redeemed_at = transaction_timestamp(),
    replay_until = transaction_timestamp() + interval '5 minutes'
WHERE request_id = $2
    AND approved_at IS NOT NULL AND cancelled_at IS NULL AND denied_at IS NULL
    AND redeemed_at IS NULL AND expires_at > transaction_timestamp()
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

type RedeemCLILoginParams struct {
	CredentialID pgtype.UUID
	RequestID    string
}

func (q *Queries) RedeemCLILogin(ctx context.Context, arg RedeemCLILoginParams) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, redeemCLILogin, arg.CredentialID, arg.RequestID)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}

const revokeCLICredential = `-- name: RevokeCLICredential :one
UPDATE cli_credentials
SET revoked_at = transaction_timestamp(), revoked_by_user_id = $1,
    revocation_idempotency_key = $2,
    revocation_request_digest = $3
WHERE credential_id = $4 AND revoked_at IS NULL
RETURNING credential_id, login_request_id, user_id, label, created_at, expires_at, revoked_at, revoked_by_user_id, revocation_idempotency_key, revocation_request_digest
`

type RevokeCLICredentialParams struct {
	UserID         pgtype.UUID
	IdempotencyKey *string
	RequestDigest  []byte
	CredentialID   string
}

func (q *Queries) RevokeCLICredential(ctx context.Context, arg RevokeCLICredentialParams) (CliCredential, error) {
	row := q.db.QueryRow(ctx, revokeCLICredential,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.CredentialID,
	)
	var i CliCredential
	err := row.Scan(
		&i.CredentialID,
		&i.LoginRequestID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevocationIdempotencyKey,
		&i.RevocationRequestDigest,
	)
	return i, err
}

const slowDownCLILoginPoll = `-- name: SlowDownCLILoginPoll :one
UPDATE cli_login_requests
SET last_polled_at = transaction_timestamp(),
    poll_interval_seconds = least(30, poll_interval_seconds + 5)
WHERE request_id = $1
RETURNING request_id, begin_idempotency_key, begin_request_digest, user_code_digest, code_generation, source_digest, label, proposed_replacement_credential_id, created_at, expires_at, last_polled_at, poll_interval_seconds, approved_at, approved_by_user_id, approved_space_id, approval_idempotency_key, approval_request_digest, prepared_credential_id, denied_at, denied_by_user_id, denial_idempotency_key, denial_request_digest, cancelled_at, resulting_credential_id, redeemed_at, replay_until
`

func (q *Queries) SlowDownCLILoginPoll(ctx context.Context, requestID string) (CliLoginRequest, error) {
	row := q.db.QueryRow(ctx, slowDownCLILoginPoll, requestID)
	var i CliLoginRequest
	err := row.Scan(
		&i.RequestID,
		&i.BeginIdempotencyKey,
		&i.BeginRequestDigest,
		&i.UserCodeDigest,
		&i.CodeGeneration,
		&i.SourceDigest,
		&i.Label,
		&i.ProposedReplacementCredentialID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastPolledAt,
		&i.PollIntervalSeconds,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.ApprovedSpaceID,
		&i.ApprovalIdempotencyKey,
		&i.ApprovalRequestDigest,
		&i.PreparedCredentialID,
		&i.DeniedAt,
		&i.DeniedByUserID,
		&i.DenialIdempotencyKey,
		&i.DenialRequestDigest,
		&i.CancelledAt,
		&i.ResultingCredentialID,
		&i.RedeemedAt,
		&i.ReplayUntil,
	)
	return i, err
}
