// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceConversationMessageHead = `-- name: AdvanceConversationMessageHead :one
UPDATE conversations
SET message_head_seq = message_head_seq + 1
WHERE conversation_id = $1
RETURNING message_head_seq
`

func (q *Queries) AdvanceConversationMessageHead(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRow(ctx, advanceConversationMessageHead, conversationID)
	var message_head_seq int64
	err := row.Scan(&message_head_seq)
	return message_head_seq, err
}

const assignConversationReply = `-- name: AssignConversationReply :one
UPDATE conversation_reply_claims
SET
    current_machine_id = $1,
    current_fence = current_fence + 1,
    lease_expires_at = clock_timestamp() + interval '5 minutes',
    context_start_seq = $2,
    context_end_seq = $3
WHERE
    source_message_id = $4
    AND current_fence = $5
    AND committed_reply_message_id IS NULL
    AND (
        current_machine_id IS NULL
        OR lease_expires_at <= clock_timestamp()
    )
RETURNING current_fence, lease_expires_at
`

type AssignConversationReplyParams struct {
	MachineID       pgtype.UUID
	ContextStartSeq *int64
	ContextEndSeq   *int64
	SourceMessageID string
	ExpectedFence   int64
}

type AssignConversationReplyRow struct {
	CurrentFence   int64
	LeaseExpiresAt pgtype.Timestamptz
}

func (q *Queries) AssignConversationReply(ctx context.Context, arg AssignConversationReplyParams) (AssignConversationReplyRow, error) {
	row := q.db.QueryRow(ctx, assignConversationReply,
		arg.MachineID,
		arg.ContextStartSeq,
		arg.ContextEndSeq,
		arg.SourceMessageID,
		arg.ExpectedFence,
	)
	var i AssignConversationReplyRow
	err := row.Scan(&i.CurrentFence, &i.LeaseExpiresAt)
	return i, err
}

const completeConversationReply = `-- name: CompleteConversationReply :execrows
UPDATE conversation_reply_claims
SET
    output_digest = $1,
    committed_reply_message_id = $2,
    committed_reply_author = 'carry',
    created_work_id = $3
WHERE
    source_message_id = $4
    AND current_machine_id = $5
    AND current_fence = $6
    AND lease_expires_at > clock_timestamp()
    AND committed_reply_message_id IS NULL
`

type CompleteConversationReplyParams struct {
	OutputDigest    []byte
	ReplyMessageID  pgtype.UUID
	CreatedWorkID   pgtype.UUID
	SourceMessageID string
	MachineID       pgtype.UUID
	Fence           int64
}

func (q *Queries) CompleteConversationReply(ctx context.Context, arg CompleteConversationReplyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeConversationReply,
		arg.OutputDigest,
		arg.ReplyMessageID,
		arg.CreatedWorkID,
		arg.SourceMessageID,
		arg.MachineID,
		arg.Fence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const conversationCursorSequence = `-- name: ConversationCursorSequence :one
SELECT message_seq
FROM conversation_messages
WHERE conversation_id = $1 AND message_id = $2
`

type ConversationCursorSequenceParams struct {
	ConversationID string
	MessageID      string
}

func (q *Queries) ConversationCursorSequence(ctx context.Context, arg ConversationCursorSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, conversationCursorSequence, arg.ConversationID, arg.MessageID)
	var message_seq int64
	err := row.Scan(&message_seq)
	return message_seq, err
}

const conversationHasUnresolvedReply = `-- name: ConversationHasUnresolvedReply :one
SELECT EXISTS (
    SELECT 1
    FROM conversation_reply_claims
    WHERE conversation_id = $1
      AND committed_reply_message_id IS NULL
)
`

func (q *Queries) ConversationHasUnresolvedReply(ctx context.Context, conversationID string) (bool, error) {
	row := q.db.QueryRow(ctx, conversationHasUnresolvedReply, conversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const conversationReplyLeaseIsCurrent = `-- name: ConversationReplyLeaseIsCurrent :one
SELECT lease_expires_at > clock_timestamp()
FROM conversation_reply_claims
WHERE source_message_id = $1
    AND lease_expires_at IS NOT NULL
`

func (q *Queries) ConversationReplyLeaseIsCurrent(ctx context.Context, sourceMessageID string) (bool, error) {
	row := q.db.QueryRow(ctx, conversationReplyLeaseIsCurrent, sourceMessageID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createConversationCarryReply = `-- name: CreateConversationCarryReply :one
INSERT INTO conversation_messages (
    message_id,
    conversation_id,
    message_seq,
    author,
    text,
    reply_to_member_message_id
) VALUES (
    $1,
    $2,
    $3,
    'carry',
    $4,
    $5
)
RETURNING message_id
`

type CreateConversationCarryReplyParams struct {
	MessageID       string
	ConversationID  string
	MessageSeq      int64
	Text            string
	SourceMessageID pgtype.UUID
}

func (q *Queries) CreateConversationCarryReply(ctx context.Context, arg CreateConversationCarryReplyParams) (string, error) {
	row := q.db.QueryRow(ctx, createConversationCarryReply,
		arg.MessageID,
		arg.ConversationID,
		arg.MessageSeq,
		arg.Text,
		arg.SourceMessageID,
	)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const createConversationMemberMessage = `-- name: CreateConversationMemberMessage :one
INSERT INTO conversation_messages (
    message_id,
    conversation_id,
    message_seq,
    author,
    author_user_id,
    text,
    member_request_id,
    request_digest
) VALUES (
    $1,
    $2,
    $3,
    'member',
    $4,
    $5,
    $6,
    $7
)
RETURNING message_id, author, text, member_request_id, message_seq, created_at
`

type CreateConversationMemberMessageParams struct {
	MessageID       string
	ConversationID  string
	MessageSeq      int64
	AuthorUserID    pgtype.UUID
	Text            string
	MemberRequestID *string
	RequestDigest   []byte
}

type CreateConversationMemberMessageRow struct {
	MessageID       string
	Author          string
	Text            string
	MemberRequestID *string
	MessageSeq      int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateConversationMemberMessage(ctx context.Context, arg CreateConversationMemberMessageParams) (CreateConversationMemberMessageRow, error) {
	row := q.db.QueryRow(ctx, createConversationMemberMessage,
		arg.MessageID,
		arg.ConversationID,
		arg.MessageSeq,
		arg.AuthorUserID,
		arg.Text,
		arg.MemberRequestID,
		arg.RequestDigest,
	)
	var i CreateConversationMemberMessageRow
	err := row.Scan(
		&i.MessageID,
		&i.Author,
		&i.Text,
		&i.MemberRequestID,
		&i.MessageSeq,
		&i.CreatedAt,
	)
	return i, err
}

const createConversationReplyClaim = `-- name: CreateConversationReplyClaim :exec
INSERT INTO conversation_reply_claims (source_message_id, conversation_id)
VALUES ($1, $2)
`

type CreateConversationReplyClaimParams struct {
	SourceMessageID string
	ConversationID  string
}

func (q *Queries) CreateConversationReplyClaim(ctx context.Context, arg CreateConversationReplyClaimParams) error {
	_, err := q.db.Exec(ctx, createConversationReplyClaim, arg.SourceMessageID, arg.ConversationID)
	return err
}

const ensureConversation = `-- name: EnsureConversation :one
INSERT INTO conversations (conversation_id, space_id, member_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (space_id, member_user_id) DO UPDATE
SET conversation_id = conversations.conversation_id
RETURNING conversation_id, message_head_seq
`

type EnsureConversationParams struct {
	ConversationID string
	SpaceID        string
	MemberUserID   string
}

type EnsureConversationRow struct {
	ConversationID string
	MessageHeadSeq int64
}

func (q *Queries) EnsureConversation(ctx context.Context, arg EnsureConversationParams) (EnsureConversationRow, error) {
	row := q.db.QueryRow(ctx, ensureConversation, arg.ConversationID, arg.SpaceID, arg.MemberUserID)
	var i EnsureConversationRow
	err := row.Scan(&i.ConversationID, &i.MessageHeadSeq)
	return i, err
}

const extendConversationReplyLease = `-- name: ExtendConversationReplyLease :one
UPDATE conversation_reply_claims
SET lease_expires_at = clock_timestamp() + interval '5 minutes'
WHERE
    source_message_id = $1
    AND current_machine_id = $2
    AND current_fence = $3
    AND lease_expires_at > clock_timestamp()
    AND committed_reply_message_id IS NULL
RETURNING lease_expires_at
`

type ExtendConversationReplyLeaseParams struct {
	SourceMessageID string
	MachineID       pgtype.UUID
	Fence           int64
}

func (q *Queries) ExtendConversationReplyLease(ctx context.Context, arg ExtendConversationReplyLeaseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, extendConversationReplyLease, arg.SourceMessageID, arg.MachineID, arg.Fence)
	var lease_expires_at pgtype.Timestamptz
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const findConversation = `-- name: FindConversation :one
SELECT conversation_id
FROM conversations
WHERE space_id = $1 AND member_user_id = $2
`

type FindConversationParams struct {
	SpaceID      string
	MemberUserID string
}

func (q *Queries) FindConversation(ctx context.Context, arg FindConversationParams) (string, error) {
	row := q.db.QueryRow(ctx, findConversation, arg.SpaceID, arg.MemberUserID)
	var conversation_id string
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const findConversationMemberRequest = `-- name: FindConversationMemberRequest :one
SELECT message_id, author, text, member_request_id, message_seq, created_at, request_digest
FROM conversation_messages
WHERE
    conversation_id = $1
    AND author = 'member'
    AND member_request_id = $2
`

type FindConversationMemberRequestParams struct {
	ConversationID  string
	MemberRequestID *string
}

type FindConversationMemberRequestRow struct {
	MessageID       string
	Author          string
	Text            string
	MemberRequestID *string
	MessageSeq      int64
	CreatedAt       pgtype.Timestamptz
	RequestDigest   []byte
}

func (q *Queries) FindConversationMemberRequest(ctx context.Context, arg FindConversationMemberRequestParams) (FindConversationMemberRequestRow, error) {
	row := q.db.QueryRow(ctx, findConversationMemberRequest, arg.ConversationID, arg.MemberRequestID)
	var i FindConversationMemberRequestRow
	err := row.Scan(
		&i.MessageID,
		&i.Author,
		&i.Text,
		&i.MemberRequestID,
		&i.MessageSeq,
		&i.CreatedAt,
		&i.RequestDigest,
	)
	return i, err
}

const listConversationContextCandidates = `-- name: ListConversationContextCandidates :many
SELECT message_seq, author, text
FROM (
    SELECT message_seq, author, text
    FROM conversation_messages
    WHERE
        conversation_id = $1
        AND message_seq <= $2
    ORDER BY message_seq DESC
    LIMIT 32
) AS newest
ORDER BY message_seq
`

type ListConversationContextCandidatesParams struct {
	ConversationID string
	ContextEndSeq  int64
}

type ListConversationContextCandidatesRow struct {
	MessageSeq int64
	Author     string
	Text       string
}

func (q *Queries) ListConversationContextCandidates(ctx context.Context, arg ListConversationContextCandidatesParams) ([]ListConversationContextCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listConversationContextCandidates, arg.ConversationID, arg.ContextEndSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationContextCandidatesRow
	for rows.Next() {
		var i ListConversationContextCandidatesRow
		if err := rows.Scan(&i.MessageSeq, &i.Author, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessagesAfter = `-- name: ListConversationMessagesAfter :many
SELECT
    message.message_id,
    message.author,
    message.text,
    message.member_request_id,
    claim.created_work_id,
    message.message_seq,
    message.created_at
FROM conversation_messages AS message
LEFT JOIN conversation_reply_claims AS claim
    ON claim.committed_reply_message_id = message.message_id
WHERE
    message.conversation_id = $1
    AND message.message_seq > $2
ORDER BY message.message_seq
LIMIT 50
`

type ListConversationMessagesAfterParams struct {
	ConversationID string
	CursorSequence int64
}

type ListConversationMessagesAfterRow struct {
	MessageID       string
	Author          string
	Text            string
	MemberRequestID *string
	CreatedWorkID   pgtype.UUID
	MessageSeq      int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListConversationMessagesAfter(ctx context.Context, arg ListConversationMessagesAfterParams) ([]ListConversationMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listConversationMessagesAfter, arg.ConversationID, arg.CursorSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationMessagesAfterRow
	for rows.Next() {
		var i ListConversationMessagesAfterRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Author,
			&i.Text,
			&i.MemberRequestID,
			&i.CreatedWorkID,
			&i.MessageSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessagesBefore = `-- name: ListConversationMessagesBefore :many
SELECT message_id, author, text, member_request_id, created_work_id, message_seq, created_at FROM (
    SELECT
        message.message_id,
        message.author,
        message.text,
        message.member_request_id,
        claim.created_work_id,
        message.message_seq,
        message.created_at
    FROM conversation_messages AS message
    LEFT JOIN conversation_reply_claims AS claim
        ON claim.committed_reply_message_id = message.message_id
    WHERE
        message.conversation_id = $1
        AND message.message_seq < $2
    ORDER BY message.message_seq DESC
    LIMIT 50
) AS prior
ORDER BY message_seq
`

type ListConversationMessagesBeforeParams struct {
	ConversationID string
	CursorSequence int64
}

type ListConversationMessagesBeforeRow struct {
	MessageID       string
	Author          string
	Text            string
	MemberRequestID *string
	CreatedWorkID   pgtype.UUID
	MessageSeq      int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListConversationMessagesBefore(ctx context.Context, arg ListConversationMessagesBeforeParams) ([]ListConversationMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listConversationMessagesBefore, arg.ConversationID, arg.CursorSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationMessagesBeforeRow
	for rows.Next() {
		var i ListConversationMessagesBeforeRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Author,
			&i.Text,
			&i.MemberRequestID,
			&i.CreatedWorkID,
			&i.MessageSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFixedConversationReplyContext = `-- name: ListFixedConversationReplyContext :many
SELECT author, text
FROM conversation_messages
WHERE
    conversation_id = $1
    AND message_seq >= $2
    AND message_seq <= $3
ORDER BY message_seq
`

type ListFixedConversationReplyContextParams struct {
	ConversationID  string
	ContextStartSeq int64
	ContextEndSeq   int64
}

type ListFixedConversationReplyContextRow struct {
	Author string
	Text   string
}

func (q *Queries) ListFixedConversationReplyContext(ctx context.Context, arg ListFixedConversationReplyContextParams) ([]ListFixedConversationReplyContextRow, error) {
	rows, err := q.db.Query(ctx, listFixedConversationReplyContext, arg.ConversationID, arg.ContextStartSeq, arg.ContextEndSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFixedConversationReplyContextRow
	for rows.Next() {
		var i ListFixedConversationReplyContextRow
		if err := rows.Scan(&i.Author, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestConversationMessages = `-- name: ListNewestConversationMessages :many
SELECT message_id, author, text, member_request_id, created_work_id, message_seq, created_at FROM (
    SELECT
        message.message_id,
        message.author,
        message.text,
        message.member_request_id,
        claim.created_work_id,
        message.message_seq,
        message.created_at
    FROM conversation_messages AS message
    LEFT JOIN conversation_reply_claims AS claim
        ON claim.committed_reply_message_id = message.message_id
    WHERE message.conversation_id = $1
    ORDER BY message.message_seq DESC
    LIMIT 50
) AS newest
ORDER BY message_seq
`

type ListNewestConversationMessagesRow struct {
	MessageID       string
	Author          string
	Text            string
	MemberRequestID *string
	CreatedWorkID   pgtype.UUID
	MessageSeq      int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListNewestConversationMessages(ctx context.Context, conversationID string) ([]ListNewestConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, listNewestConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewestConversationMessagesRow
	for rows.Next() {
		var i ListNewestConversationMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Author,
			&i.Text,
			&i.MemberRequestID,
			&i.CreatedWorkID,
			&i.MessageSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveConversationMembership = `-- name: LockActiveConversationMembership :one
SELECT version
FROM space_memberships
WHERE
    space_id = $1
    AND user_id = $2
    AND revoked_at IS NULL
FOR SHARE
`

type LockActiveConversationMembershipParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) LockActiveConversationMembership(ctx context.Context, arg LockActiveConversationMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockActiveConversationMembership, arg.SpaceID, arg.UserID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockConversation = `-- name: LockConversation :one
SELECT conversation_id, message_head_seq
FROM conversations
WHERE conversation_id = $1
FOR UPDATE
`

type LockConversationRow struct {
	ConversationID string
	MessageHeadSeq int64
}

func (q *Queries) LockConversation(ctx context.Context, conversationID string) (LockConversationRow, error) {
	row := q.db.QueryRow(ctx, lockConversation, conversationID)
	var i LockConversationRow
	err := row.Scan(&i.ConversationID, &i.MessageHeadSeq)
	return i, err
}

const lockConversationReplyForClaim = `-- name: LockConversationReplyForClaim :one
SELECT
    claim.source_message_id,
    claim.conversation_id,
    claim.current_machine_id,
    claim.current_fence,
    claim.lease_expires_at,
    claim.context_start_seq,
    claim.context_end_seq,
    source.message_seq AS source_message_seq
FROM conversation_reply_claims AS claim
JOIN conversations AS conversation
    ON conversation.conversation_id = claim.conversation_id
JOIN conversation_messages AS source
    ON source.message_id = claim.source_message_id
JOIN space_memberships AS membership
    ON membership.space_id = conversation.space_id
    AND membership.user_id = conversation.member_user_id
WHERE
    conversation.space_id = $1
    AND membership.revoked_at IS NULL
    AND claim.committed_reply_message_id IS NULL
    AND (
        claim.current_machine_id IS NULL
        OR claim.lease_expires_at <= clock_timestamp()
    )
ORDER BY source.created_at, source.message_id
LIMIT 1
FOR UPDATE OF claim SKIP LOCKED
FOR SHARE OF membership
`

type LockConversationReplyForClaimRow struct {
	SourceMessageID  string
	ConversationID   string
	CurrentMachineID pgtype.UUID
	CurrentFence     int64
	LeaseExpiresAt   pgtype.Timestamptz
	ContextStartSeq  *int64
	ContextEndSeq    *int64
	SourceMessageSeq int64
}

func (q *Queries) LockConversationReplyForClaim(ctx context.Context, spaceID string) (LockConversationReplyForClaimRow, error) {
	row := q.db.QueryRow(ctx, lockConversationReplyForClaim, spaceID)
	var i LockConversationReplyForClaimRow
	err := row.Scan(
		&i.SourceMessageID,
		&i.ConversationID,
		&i.CurrentMachineID,
		&i.CurrentFence,
		&i.LeaseExpiresAt,
		&i.ContextStartSeq,
		&i.ContextEndSeq,
		&i.SourceMessageSeq,
	)
	return i, err
}

const lockConversationReplyForCommit = `-- name: LockConversationReplyForCommit :one
SELECT
    claim.conversation_id,
    conversation.space_id,
    conversation.member_user_id,
    conversation.message_head_seq,
    source.message_seq AS source_message_seq,
    claim.current_machine_id,
    claim.current_fence,
    claim.output_digest,
    claim.committed_reply_message_id,
    claim.created_work_id
FROM conversation_reply_claims AS claim
JOIN conversations AS conversation
    ON conversation.conversation_id = claim.conversation_id
JOIN conversation_messages AS source
    ON source.message_id = claim.source_message_id
JOIN space_memberships AS membership
    ON membership.space_id = conversation.space_id
    AND membership.user_id = conversation.member_user_id
WHERE
    claim.source_message_id = $1
    AND conversation.space_id = $2
    AND membership.revoked_at IS NULL
FOR UPDATE OF claim, conversation
FOR SHARE OF membership
`

type LockConversationReplyForCommitParams struct {
	SourceMessageID string
	SpaceID         string
}

type LockConversationReplyForCommitRow struct {
	ConversationID          string
	SpaceID                 string
	MemberUserID            string
	MessageHeadSeq          int64
	SourceMessageSeq        int64
	CurrentMachineID        pgtype.UUID
	CurrentFence            int64
	OutputDigest            []byte
	CommittedReplyMessageID pgtype.UUID
	CreatedWorkID           pgtype.UUID
}

func (q *Queries) LockConversationReplyForCommit(ctx context.Context, arg LockConversationReplyForCommitParams) (LockConversationReplyForCommitRow, error) {
	row := q.db.QueryRow(ctx, lockConversationReplyForCommit, arg.SourceMessageID, arg.SpaceID)
	var i LockConversationReplyForCommitRow
	err := row.Scan(
		&i.ConversationID,
		&i.SpaceID,
		&i.MemberUserID,
		&i.MessageHeadSeq,
		&i.SourceMessageSeq,
		&i.CurrentMachineID,
		&i.CurrentFence,
		&i.OutputDigest,
		&i.CommittedReplyMessageID,
		&i.CreatedWorkID,
	)
	return i, err
}

const lockConversationReplyForRenew = `-- name: LockConversationReplyForRenew :one
SELECT claim.source_message_id
FROM conversation_reply_claims AS claim
JOIN conversations AS conversation
    ON conversation.conversation_id = claim.conversation_id
JOIN space_memberships AS membership
    ON membership.space_id = conversation.space_id
    AND membership.user_id = conversation.member_user_id
WHERE
    claim.source_message_id = $1
    AND conversation.space_id = $2
    AND membership.revoked_at IS NULL
    AND claim.current_machine_id = $3
    AND claim.current_fence = $4
    AND claim.lease_expires_at > clock_timestamp()
    AND claim.committed_reply_message_id IS NULL
FOR UPDATE OF claim
FOR SHARE OF membership
`

type LockConversationReplyForRenewParams struct {
	SourceMessageID string
	SpaceID         string
	MachineID       pgtype.UUID
	Fence           int64
}

func (q *Queries) LockConversationReplyForRenew(ctx context.Context, arg LockConversationReplyForRenewParams) (string, error) {
	row := q.db.QueryRow(ctx, lockConversationReplyForRenew,
		arg.SourceMessageID,
		arg.SpaceID,
		arg.MachineID,
		arg.Fence,
	)
	var source_message_id string
	err := row.Scan(&source_message_id)
	return source_message_id, err
}
