// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_login.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailChallenge = `-- name: ConsumeEmailChallenge :execrows
UPDATE email_login_challenges
SET
    consumed_at = transaction_timestamp(),
    user_id = $1,
    browser_session_id = $2
WHERE challenge_id = $3
    AND consumed_at IS NULL
    AND invalidated_at IS NULL
    AND expires_at > transaction_timestamp()
    AND attempts_used < 5
`

type ConsumeEmailChallengeParams struct {
	UserID      pgtype.UUID
	SessionID   pgtype.UUID
	ChallengeID string
}

func (q *Queries) ConsumeEmailChallenge(ctx context.Context, arg ConsumeEmailChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeEmailChallenge, arg.UserID, arg.SessionID, arg.ChallengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRecentEmailChallenges = `-- name: CountRecentEmailChallenges :one
SELECT count(*)
FROM email_login_challenges
WHERE canonical_email = $1
    AND created_at > transaction_timestamp() - interval '1 hour'
`

func (q *Queries) CountRecentEmailChallenges(ctx context.Context, canonicalEmail string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEmailChallenges, canonicalEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentSourceChallenges = `-- name: CountRecentSourceChallenges :one
SELECT count(*)
FROM email_login_challenges
WHERE source_digest = $1
    AND created_at > transaction_timestamp() - interval '1 hour'
`

func (q *Queries) CountRecentSourceChallenges(ctx context.Context, sourceDigest []byte) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSourceChallenges, sourceDigest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailChallenge = `-- name: CreateEmailChallenge :one
INSERT INTO email_login_challenges (
    challenge_id,
    canonical_email,
    code_digest,
    source_digest,
    payload_digest,
    request_idempotency_key,
    request_digest,
    purpose,
    target_user_id,
    initiating_session_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    transaction_timestamp() + interval '5 minutes'
)
RETURNING challenge_id, canonical_email, code_digest, source_digest, payload_digest, request_idempotency_key, request_digest, submission_state, provider_message_id, attempts_used, created_at, expires_at, invalidated_at, consumed_at, user_id, browser_session_id, purpose, target_user_id, initiating_session_id
`

type CreateEmailChallengeParams struct {
	ChallengeID           string
	CanonicalEmail        string
	CodeDigest            []byte
	SourceDigest          []byte
	PayloadDigest         []byte
	RequestIdempotencyKey string
	RequestDigest         []byte
	Purpose               string
	TargetUserID          pgtype.UUID
	InitiatingSessionID   pgtype.UUID
}

func (q *Queries) CreateEmailChallenge(ctx context.Context, arg CreateEmailChallengeParams) (EmailLoginChallenge, error) {
	row := q.db.QueryRow(ctx, createEmailChallenge,
		arg.ChallengeID,
		arg.CanonicalEmail,
		arg.CodeDigest,
		arg.SourceDigest,
		arg.PayloadDigest,
		arg.RequestIdempotencyKey,
		arg.RequestDigest,
		arg.Purpose,
		arg.TargetUserID,
		arg.InitiatingSessionID,
	)
	var i EmailLoginChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.CanonicalEmail,
		&i.CodeDigest,
		&i.SourceDigest,
		&i.PayloadDigest,
		&i.RequestIdempotencyKey,
		&i.RequestDigest,
		&i.SubmissionState,
		&i.ProviderMessageID,
		&i.AttemptsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.InvalidatedAt,
		&i.ConsumedAt,
		&i.UserID,
		&i.BrowserSessionID,
		&i.Purpose,
		&i.TargetUserID,
		&i.InitiatingSessionID,
	)
	return i, err
}

const createEmailIdentity = `-- name: CreateEmailIdentity :exec
INSERT INTO email_identities (canonical_email, user_id)
VALUES ($1, $2)
`

type CreateEmailIdentityParams struct {
	CanonicalEmail string
	UserID         string
}

func (q *Queries) CreateEmailIdentity(ctx context.Context, arg CreateEmailIdentityParams) error {
	_, err := q.db.Exec(ctx, createEmailIdentity, arg.CanonicalEmail, arg.UserID)
	return err
}

const createEmailUser = `-- name: CreateEmailUser :exec
INSERT INTO carry_users (user_id, display_name)
VALUES ($1, NULL)
`

func (q *Queries) CreateEmailUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, createEmailUser, userID)
	return err
}

const emailLoginDatabaseTime = `-- name: EmailLoginDatabaseTime :one
SELECT transaction_timestamp()::timestamptz
`

func (q *Queries) EmailLoginDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, emailLoginDatabaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const invalidateCurrentEmailChallenges = `-- name: InvalidateCurrentEmailChallenges :exec
UPDATE email_login_challenges
SET invalidated_at = transaction_timestamp()
WHERE canonical_email = $1
    AND invalidated_at IS NULL
    AND consumed_at IS NULL
`

func (q *Queries) InvalidateCurrentEmailChallenges(ctx context.Context, canonicalEmail string) error {
	_, err := q.db.Exec(ctx, invalidateCurrentEmailChallenges, canonicalEmail)
	return err
}

const loadEmailAttempt = `-- name: LoadEmailAttempt :one
SELECT challenge_id, idempotency_key, request_digest, result, created_at
FROM email_login_attempts
WHERE challenge_id = $1
    AND idempotency_key = $2
`

type LoadEmailAttemptParams struct {
	ChallengeID    string
	IdempotencyKey string
}

func (q *Queries) LoadEmailAttempt(ctx context.Context, arg LoadEmailAttemptParams) (EmailLoginAttempt, error) {
	row := q.db.QueryRow(ctx, loadEmailAttempt, arg.ChallengeID, arg.IdempotencyKey)
	var i EmailLoginAttempt
	err := row.Scan(
		&i.ChallengeID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const loadEmailChallengeByRequestKey = `-- name: LoadEmailChallengeByRequestKey :one
SELECT challenge_id, canonical_email, code_digest, source_digest, payload_digest, request_idempotency_key, request_digest, submission_state, provider_message_id, attempts_used, created_at, expires_at, invalidated_at, consumed_at, user_id, browser_session_id, purpose, target_user_id, initiating_session_id
FROM email_login_challenges
WHERE request_idempotency_key = $1
`

func (q *Queries) LoadEmailChallengeByRequestKey(ctx context.Context, requestIdempotencyKey string) (EmailLoginChallenge, error) {
	row := q.db.QueryRow(ctx, loadEmailChallengeByRequestKey, requestIdempotencyKey)
	var i EmailLoginChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.CanonicalEmail,
		&i.CodeDigest,
		&i.SourceDigest,
		&i.PayloadDigest,
		&i.RequestIdempotencyKey,
		&i.RequestDigest,
		&i.SubmissionState,
		&i.ProviderMessageID,
		&i.AttemptsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.InvalidatedAt,
		&i.ConsumedAt,
		&i.UserID,
		&i.BrowserSessionID,
		&i.Purpose,
		&i.TargetUserID,
		&i.InitiatingSessionID,
	)
	return i, err
}

const loadEmailIdentity = `-- name: LoadEmailIdentity :one
SELECT user_id
FROM email_identities
WHERE canonical_email = $1
FOR UPDATE
`

func (q *Queries) LoadEmailIdentity(ctx context.Context, canonicalEmail string) (string, error) {
	row := q.db.QueryRow(ctx, loadEmailIdentity, canonicalEmail)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const loadLatestEmailChallenge = `-- name: LoadLatestEmailChallenge :one
SELECT challenge_id, canonical_email, code_digest, source_digest, payload_digest, request_idempotency_key, request_digest, submission_state, provider_message_id, attempts_used, created_at, expires_at, invalidated_at, consumed_at, user_id, browser_session_id, purpose, target_user_id, initiating_session_id
FROM email_login_challenges
WHERE canonical_email = $1
ORDER BY created_at DESC, challenge_id DESC
LIMIT 1
`

func (q *Queries) LoadLatestEmailChallenge(ctx context.Context, canonicalEmail string) (EmailLoginChallenge, error) {
	row := q.db.QueryRow(ctx, loadLatestEmailChallenge, canonicalEmail)
	var i EmailLoginChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.CanonicalEmail,
		&i.CodeDigest,
		&i.SourceDigest,
		&i.PayloadDigest,
		&i.RequestIdempotencyKey,
		&i.RequestDigest,
		&i.SubmissionState,
		&i.ProviderMessageID,
		&i.AttemptsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.InvalidatedAt,
		&i.ConsumedAt,
		&i.UserID,
		&i.BrowserSessionID,
		&i.Purpose,
		&i.TargetUserID,
		&i.InitiatingSessionID,
	)
	return i, err
}

const lockEmailChallenge = `-- name: LockEmailChallenge :one
SELECT challenge_id, canonical_email, code_digest, source_digest, payload_digest, request_idempotency_key, request_digest, submission_state, provider_message_id, attempts_used, created_at, expires_at, invalidated_at, consumed_at, user_id, browser_session_id, purpose, target_user_id, initiating_session_id
FROM email_login_challenges
WHERE challenge_id = $1
FOR UPDATE
`

func (q *Queries) LockEmailChallenge(ctx context.Context, challengeID string) (EmailLoginChallenge, error) {
	row := q.db.QueryRow(ctx, lockEmailChallenge, challengeID)
	var i EmailLoginChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.CanonicalEmail,
		&i.CodeDigest,
		&i.SourceDigest,
		&i.PayloadDigest,
		&i.RequestIdempotencyKey,
		&i.RequestDigest,
		&i.SubmissionState,
		&i.ProviderMessageID,
		&i.AttemptsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.InvalidatedAt,
		&i.ConsumedAt,
		&i.UserID,
		&i.BrowserSessionID,
		&i.Purpose,
		&i.TargetUserID,
		&i.InitiatingSessionID,
	)
	return i, err
}

const lockEmailLogin = `-- name: LockEmailLogin :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockEmailLogin(ctx context.Context, canonicalEmail string) error {
	_, err := q.db.Exec(ctx, lockEmailLogin, canonicalEmail)
	return err
}

const lockEmailRequest = `-- name: LockEmailRequest :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 2))
`

func (q *Queries) LockEmailRequest(ctx context.Context, requestIdempotencyKey string) error {
	_, err := q.db.Exec(ctx, lockEmailRequest, requestIdempotencyKey)
	return err
}

const lockEmailSource = `-- name: LockEmailSource :exec
SELECT pg_advisory_xact_lock(hashtextextended(encode($1::bytea, 'hex'), 1))
`

func (q *Queries) LockEmailSource(ctx context.Context, sourceDigest []byte) error {
	_, err := q.db.Exec(ctx, lockEmailSource, sourceDigest)
	return err
}

const recordEmailSubmission = `-- name: RecordEmailSubmission :one
UPDATE email_login_challenges
SET
    submission_state = $1,
    provider_message_id = $2
WHERE challenge_id = $3
    AND payload_digest = $4
    AND submission_state IN ('prepared', 'unknown')
RETURNING challenge_id, canonical_email, code_digest, source_digest, payload_digest, request_idempotency_key, request_digest, submission_state, provider_message_id, attempts_used, created_at, expires_at, invalidated_at, consumed_at, user_id, browser_session_id, purpose, target_user_id, initiating_session_id
`

type RecordEmailSubmissionParams struct {
	SubmissionState   string
	ProviderMessageID *string
	ChallengeID       string
	PayloadDigest     []byte
}

func (q *Queries) RecordEmailSubmission(ctx context.Context, arg RecordEmailSubmissionParams) (EmailLoginChallenge, error) {
	row := q.db.QueryRow(ctx, recordEmailSubmission,
		arg.SubmissionState,
		arg.ProviderMessageID,
		arg.ChallengeID,
		arg.PayloadDigest,
	)
	var i EmailLoginChallenge
	err := row.Scan(
		&i.ChallengeID,
		&i.CanonicalEmail,
		&i.CodeDigest,
		&i.SourceDigest,
		&i.PayloadDigest,
		&i.RequestIdempotencyKey,
		&i.RequestDigest,
		&i.SubmissionState,
		&i.ProviderMessageID,
		&i.AttemptsUsed,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.InvalidatedAt,
		&i.ConsumedAt,
		&i.UserID,
		&i.BrowserSessionID,
		&i.Purpose,
		&i.TargetUserID,
		&i.InitiatingSessionID,
	)
	return i, err
}

const recordInvalidEmailAttempt = `-- name: RecordInvalidEmailAttempt :exec
INSERT INTO email_login_attempts (
    challenge_id,
    idempotency_key,
    request_digest,
    result
) VALUES (
    $1,
    $2,
    $3,
    'invalid'
)
`

type RecordInvalidEmailAttemptParams struct {
	ChallengeID    string
	IdempotencyKey string
	RequestDigest  []byte
}

func (q *Queries) RecordInvalidEmailAttempt(ctx context.Context, arg RecordInvalidEmailAttemptParams) error {
	_, err := q.db.Exec(ctx, recordInvalidEmailAttempt, arg.ChallengeID, arg.IdempotencyKey, arg.RequestDigest)
	return err
}

const recordSuccessfulEmailAttempt = `-- name: RecordSuccessfulEmailAttempt :exec
INSERT INTO email_login_attempts (
    challenge_id,
    idempotency_key,
    request_digest,
    result
) VALUES (
    $1,
    $2,
    $3,
    'succeeded'
)
`

type RecordSuccessfulEmailAttemptParams struct {
	ChallengeID    string
	IdempotencyKey string
	RequestDigest  []byte
}

func (q *Queries) RecordSuccessfulEmailAttempt(ctx context.Context, arg RecordSuccessfulEmailAttemptParams) error {
	_, err := q.db.Exec(ctx, recordSuccessfulEmailAttempt, arg.ChallengeID, arg.IdempotencyKey, arg.RequestDigest)
	return err
}

const spendEmailChallengeAttempt = `-- name: SpendEmailChallengeAttempt :execrows
UPDATE email_login_challenges
SET attempts_used = attempts_used + 1
WHERE challenge_id = $1
    AND attempts_used < 5
`

func (q *Queries) SpendEmailChallengeAttempt(ctx context.Context, challengeID string) (int64, error) {
	result, err := q.db.Exec(ctx, spendEmailChallengeAttempt, challengeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
