// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_login.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExternalLoginExchange = `-- name: ClaimExternalLoginExchange :execrows
UPDATE external_login_transactions
SET
    status = 'exchanging',
    callback_digest = $1
WHERE transaction_id = $2
    AND provider = $3
    AND status = 'prepared'
    AND expires_at > transaction_timestamp()
`

type ClaimExternalLoginExchangeParams struct {
	CallbackDigest []byte
	TransactionID  string
	Provider       string
}

func (q *Queries) ClaimExternalLoginExchange(ctx context.Context, arg ClaimExternalLoginExchangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimExternalLoginExchange, arg.CallbackDigest, arg.TransactionID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeExternalLogin = `-- name: CompleteExternalLogin :execrows
UPDATE external_login_transactions
SET
    status = 'succeeded',
    completed_at = transaction_timestamp(),
    user_id = $1,
    browser_session_id = $2
WHERE transaction_id = $3
    AND provider = $4
    AND status = 'exchanging'
    AND callback_digest = $5
    AND expires_at > transaction_timestamp()
`

type CompleteExternalLoginParams struct {
	UserID         pgtype.UUID
	SessionID      pgtype.UUID
	TransactionID  string
	Provider       string
	CallbackDigest []byte
}

func (q *Queries) CompleteExternalLogin(ctx context.Context, arg CompleteExternalLoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeExternalLogin,
		arg.UserID,
		arg.SessionID,
		arg.TransactionID,
		arg.Provider,
		arg.CallbackDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createExternalLogin = `-- name: CreateExternalLogin :one
INSERT INTO external_login_transactions (
    transaction_id,
    provider,
    purpose,
    target_user_id,
    initiating_session_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    transaction_timestamp() + interval '10 minutes'
)
RETURNING expires_at
`

type CreateExternalLoginParams struct {
	TransactionID       string
	Provider            string
	Purpose             string
	TargetUserID        pgtype.UUID
	InitiatingSessionID pgtype.UUID
}

func (q *Queries) CreateExternalLogin(ctx context.Context, arg CreateExternalLoginParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createExternalLogin,
		arg.TransactionID,
		arg.Provider,
		arg.Purpose,
		arg.TargetUserID,
		arg.InitiatingSessionID,
	)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const createExternalLoginUser = `-- name: CreateExternalLoginUser :exec
INSERT INTO carry_users (user_id, display_name)
VALUES ($1, NULL)
`

func (q *Queries) CreateExternalLoginUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, createExternalLoginUser, userID)
	return err
}

const createGitHubIdentity = `-- name: CreateGitHubIdentity :exec
INSERT INTO github_identities (github_user_id, user_id)
VALUES ($1, $2)
`

type CreateGitHubIdentityParams struct {
	GithubUserID int64
	UserID       string
}

func (q *Queries) CreateGitHubIdentity(ctx context.Context, arg CreateGitHubIdentityParams) error {
	_, err := q.db.Exec(ctx, createGitHubIdentity, arg.GithubUserID, arg.UserID)
	return err
}

const createGoogleIdentity = `-- name: CreateGoogleIdentity :exec
INSERT INTO google_identities (issuer, subject, user_id)
VALUES ($1, $2, $3)
`

type CreateGoogleIdentityParams struct {
	Issuer  string
	Subject string
	UserID  string
}

func (q *Queries) CreateGoogleIdentity(ctx context.Context, arg CreateGoogleIdentityParams) error {
	_, err := q.db.Exec(ctx, createGoogleIdentity, arg.Issuer, arg.Subject, arg.UserID)
	return err
}

const externalLoginDatabaseTime = `-- name: ExternalLoginDatabaseTime :one
SELECT transaction_timestamp()::timestamptz
`

func (q *Queries) ExternalLoginDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, externalLoginDatabaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const finishExternalLoginWithoutAuthority = `-- name: FinishExternalLoginWithoutAuthority :execrows
UPDATE external_login_transactions
SET
    status = $1,
    callback_digest = $2,
    completed_at = transaction_timestamp()
WHERE transaction_id = $3
    AND provider = $4
    AND status = 'prepared'
    AND expires_at > transaction_timestamp()
`

type FinishExternalLoginWithoutAuthorityParams struct {
	Status         string
	CallbackDigest []byte
	TransactionID  string
	Provider       string
}

func (q *Queries) FinishExternalLoginWithoutAuthority(ctx context.Context, arg FinishExternalLoginWithoutAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishExternalLoginWithoutAuthority,
		arg.Status,
		arg.CallbackDigest,
		arg.TransactionID,
		arg.Provider,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const loadGitHubIdentity = `-- name: LoadGitHubIdentity :one
SELECT user_id
FROM github_identities
WHERE github_user_id = $1
FOR UPDATE
`

func (q *Queries) LoadGitHubIdentity(ctx context.Context, githubUserID int64) (string, error) {
	row := q.db.QueryRow(ctx, loadGitHubIdentity, githubUserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const loadGoogleIdentity = `-- name: LoadGoogleIdentity :one
SELECT user_id
FROM google_identities
WHERE issuer = $1 AND subject = $2
FOR UPDATE
`

type LoadGoogleIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) LoadGoogleIdentity(ctx context.Context, arg LoadGoogleIdentityParams) (string, error) {
	row := q.db.QueryRow(ctx, loadGoogleIdentity, arg.Issuer, arg.Subject)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const lockExternalLogin = `-- name: LockExternalLogin :one
SELECT transaction_id, provider, status, callback_digest, created_at, expires_at, completed_at, user_id, browser_session_id, purpose, target_user_id, initiating_session_id
FROM external_login_transactions
WHERE transaction_id = $1
FOR UPDATE
`

func (q *Queries) LockExternalLogin(ctx context.Context, transactionID string) (ExternalLoginTransaction, error) {
	row := q.db.QueryRow(ctx, lockExternalLogin, transactionID)
	var i ExternalLoginTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.Provider,
		&i.Status,
		&i.CallbackDigest,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.UserID,
		&i.BrowserSessionID,
		&i.Purpose,
		&i.TargetUserID,
		&i.InitiatingSessionID,
	)
	return i, err
}

const lockGitHubIdentityKey = `-- name: LockGitHubIdentityKey :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::bigint::text, 8)
)
`

func (q *Queries) LockGitHubIdentityKey(ctx context.Context, githubUserID int64) error {
	_, err := q.db.Exec(ctx, lockGitHubIdentityKey, githubUserID)
	return err
}

const lockGoogleIdentityKey = `-- name: LockGoogleIdentityKey :exec
SELECT pg_advisory_xact_lock(
    hashtextextended($1::text || ':' || $2::text, 7)
)
`

type LockGoogleIdentityKeyParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) LockGoogleIdentityKey(ctx context.Context, arg LockGoogleIdentityKeyParams) error {
	_, err := q.db.Exec(ctx, lockGoogleIdentityKey, arg.Issuer, arg.Subject)
	return err
}

const markExternalLoginUnknown = `-- name: MarkExternalLoginUnknown :execrows
UPDATE external_login_transactions
SET
    status = 'unknown',
    completed_at = transaction_timestamp()
WHERE transaction_id = $1
    AND provider = $2
    AND status = 'exchanging'
    AND callback_digest = $3
`

type MarkExternalLoginUnknownParams struct {
	TransactionID  string
	Provider       string
	CallbackDigest []byte
}

func (q *Queries) MarkExternalLoginUnknown(ctx context.Context, arg MarkExternalLoginUnknownParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExternalLoginUnknown, arg.TransactionID, arg.Provider, arg.CallbackDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectExternalLogin = `-- name: RejectExternalLogin :execrows
UPDATE external_login_transactions
SET
    status = 'rejected',
    completed_at = transaction_timestamp()
WHERE transaction_id = $1
    AND provider = $2
    AND status = 'exchanging'
    AND callback_digest = $3
`

type RejectExternalLoginParams struct {
	TransactionID  string
	Provider       string
	CallbackDigest []byte
}

func (q *Queries) RejectExternalLogin(ctx context.Context, arg RejectExternalLoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectExternalLogin, arg.TransactionID, arg.Provider, arg.CallbackDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
