// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_methods.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIdentityMethods = `-- name: CountIdentityMethods :one
WITH target AS (SELECT $1::uuid AS target_user_id)
SELECT
    (SELECT count(*) FROM email_identities, target WHERE email_identities.user_id = target.target_user_id)
    + (SELECT count(*) FROM google_identities, target WHERE google_identities.user_id = target.target_user_id)
    + (SELECT count(*) FROM github_identities, target WHERE github_identities.user_id = target.target_user_id) AS method_count
`

func (q *Queries) CountIdentityMethods(ctx context.Context, targetUserID string) (int32, error) {
	row := q.db.QueryRow(ctx, countIdentityMethods, targetUserID)
	var method_count int32
	err := row.Scan(&method_count)
	return method_count, err
}

const deleteEmailMethod = `-- name: DeleteEmailMethod :execrows
DELETE FROM email_identities
WHERE user_id = $1
`

func (q *Queries) DeleteEmailMethod(ctx context.Context, targetUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmailMethod, targetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGitHubMethod = `-- name: DeleteGitHubMethod :execrows
DELETE FROM github_identities
WHERE user_id = $1
`

func (q *Queries) DeleteGitHubMethod(ctx context.Context, targetUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitHubMethod, targetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGoogleMethod = `-- name: DeleteGoogleMethod :execrows
DELETE FROM google_identities
WHERE user_id = $1
`

func (q *Queries) DeleteGoogleMethod(ctx context.Context, targetUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoogleMethod, targetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityMethodDatabaseTime = `-- name: IdentityMethodDatabaseTime :one
SELECT transaction_timestamp()::timestamptz
`

func (q *Queries) IdentityMethodDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, identityMethodDatabaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const loadEmailMethodForUser = `-- name: LoadEmailMethodForUser :one
SELECT canonical_email
FROM email_identities
WHERE user_id = $1
`

func (q *Queries) LoadEmailMethodForUser(ctx context.Context, targetUserID string) (string, error) {
	row := q.db.QueryRow(ctx, loadEmailMethodForUser, targetUserID)
	var canonical_email string
	err := row.Scan(&canonical_email)
	return canonical_email, err
}

const loadGitHubMethodForUser = `-- name: LoadGitHubMethodForUser :one
SELECT github_user_id
FROM github_identities
WHERE user_id = $1
`

func (q *Queries) LoadGitHubMethodForUser(ctx context.Context, targetUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, loadGitHubMethodForUser, targetUserID)
	var github_user_id int64
	err := row.Scan(&github_user_id)
	return github_user_id, err
}

const loadGoogleMethodForUser = `-- name: LoadGoogleMethodForUser :one
SELECT issuer, subject
FROM google_identities
WHERE user_id = $1
`

type LoadGoogleMethodForUserRow struct {
	Issuer  string
	Subject string
}

func (q *Queries) LoadGoogleMethodForUser(ctx context.Context, targetUserID string) (LoadGoogleMethodForUserRow, error) {
	row := q.db.QueryRow(ctx, loadGoogleMethodForUser, targetUserID)
	var i LoadGoogleMethodForUserRow
	err := row.Scan(&i.Issuer, &i.Subject)
	return i, err
}

const loadIdentityMethodUnlinkReplay = `-- name: LoadIdentityMethodUnlinkReplay :one
SELECT user_id, initiating_session_id, method, idempotency_key, request_digest, replacement_session_id, completed_at
FROM identity_method_unlinks
WHERE initiating_session_id = $1
    AND idempotency_key = $2
`

type LoadIdentityMethodUnlinkReplayParams struct {
	InitiatingSessionID string
	IdempotencyKey      string
}

func (q *Queries) LoadIdentityMethodUnlinkReplay(ctx context.Context, arg LoadIdentityMethodUnlinkReplayParams) (IdentityMethodUnlink, error) {
	row := q.db.QueryRow(ctx, loadIdentityMethodUnlinkReplay, arg.InitiatingSessionID, arg.IdempotencyKey)
	var i IdentityMethodUnlink
	err := row.Scan(
		&i.UserID,
		&i.InitiatingSessionID,
		&i.Method,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ReplacementSessionID,
		&i.CompletedAt,
	)
	return i, err
}

const loadIdentityMethods = `-- name: LoadIdentityMethods :one
WITH target AS (SELECT $1::uuid AS target_user_id)
SELECT
    EXISTS(SELECT 1 FROM email_identities, target WHERE email_identities.user_id = target.target_user_id) AS has_email,
    EXISTS(SELECT 1 FROM google_identities, target WHERE google_identities.user_id = target.target_user_id) AS has_google,
    EXISTS(SELECT 1 FROM github_identities, target WHERE github_identities.user_id = target.target_user_id) AS has_github
`

type LoadIdentityMethodsRow struct {
	HasEmail  bool
	HasGoogle bool
	HasGithub bool
}

func (q *Queries) LoadIdentityMethods(ctx context.Context, targetUserID string) (LoadIdentityMethodsRow, error) {
	row := q.db.QueryRow(ctx, loadIdentityMethods, targetUserID)
	var i LoadIdentityMethodsRow
	err := row.Scan(&i.HasEmail, &i.HasGoogle, &i.HasGithub)
	return i, err
}

const lockBrowserSessionForIdentityChange = `-- name: LockBrowserSessionForIdentityChange :one
SELECT user_id, created_at, expires_at, revoked_at, session_id, identity_proved_at, identity_proof_method
FROM browser_sessions
WHERE session_id = $1
FOR UPDATE
`

func (q *Queries) LockBrowserSessionForIdentityChange(ctx context.Context, sessionID string) (BrowserSession, error) {
	row := q.db.QueryRow(ctx, lockBrowserSessionForIdentityChange, sessionID)
	var i BrowserSession
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.SessionID,
		&i.IdentityProvedAt,
		&i.IdentityProofMethod,
	)
	return i, err
}

const lockUserForIdentityChange = `-- name: LockUserForIdentityChange :one
SELECT user_id
FROM carry_users
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockUserForIdentityChange(ctx context.Context, targetUserID string) (string, error) {
	row := q.db.QueryRow(ctx, lockUserForIdentityChange, targetUserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const recordIdentityMethodUnlink = `-- name: RecordIdentityMethodUnlink :exec
INSERT INTO identity_method_unlinks (
    user_id,
    initiating_session_id,
    method,
    idempotency_key,
    request_digest,
    replacement_session_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type RecordIdentityMethodUnlinkParams struct {
	UserID               string
	InitiatingSessionID  string
	Method               string
	IdempotencyKey       string
	RequestDigest        []byte
	ReplacementSessionID string
}

func (q *Queries) RecordIdentityMethodUnlink(ctx context.Context, arg RecordIdentityMethodUnlinkParams) error {
	_, err := q.db.Exec(ctx, recordIdentityMethodUnlink,
		arg.UserID,
		arg.InitiatingSessionID,
		arg.Method,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.ReplacementSessionID,
	)
	return err
}

const revokeExactBrowserSession = `-- name: RevokeExactBrowserSession :execrows
UPDATE browser_sessions
SET revoked_at = statement_timestamp()
WHERE session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeExactBrowserSession(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeExactBrowserSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserBrowserSessions = `-- name: RevokeUserBrowserSessions :execrows
UPDATE browser_sessions
SET revoked_at = statement_timestamp()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserBrowserSessions(ctx context.Context, targetUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserBrowserSessions, targetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
