// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machine.sql

package dbsqlc

import (
	"context"
)

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (
    machine_id, space_id, display_name, public_key_der, certificate_pem,
    certificate_serial, enrolled_by_user_id, enrollment_idempotency_key
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
ON CONFLICT (space_id, enrolled_by_user_id, enrollment_idempotency_key) DO NOTHING
RETURNING machine_id, space_id, display_name, certificate_pem, public_key_der
`

type CreateMachineParams struct {
	MachineID                string
	SpaceID                  string
	DisplayName              string
	PublicKeyDer             []byte
	CertificatePem           []byte
	CertificateSerial        string
	EnrolledByUserID         string
	EnrollmentIdempotencyKey string
}

type CreateMachineRow struct {
	MachineID      string
	SpaceID        string
	DisplayName    string
	CertificatePem []byte
	PublicKeyDer   []byte
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (CreateMachineRow, error) {
	row := q.db.QueryRow(ctx, createMachine,
		arg.MachineID,
		arg.SpaceID,
		arg.DisplayName,
		arg.PublicKeyDer,
		arg.CertificatePem,
		arg.CertificateSerial,
		arg.EnrolledByUserID,
		arg.EnrollmentIdempotencyKey,
	)
	var i CreateMachineRow
	err := row.Scan(
		&i.MachineID,
		&i.SpaceID,
		&i.DisplayName,
		&i.CertificatePem,
		&i.PublicKeyDer,
	)
	return i, err
}

const findEnrollmentByIdempotency = `-- name: FindEnrollmentByIdempotency :one
SELECT machine_id, space_id, display_name, certificate_pem, public_key_der
FROM machines
WHERE space_id = $1
  AND enrolled_by_user_id = $2
  AND enrollment_idempotency_key = $3
`

type FindEnrollmentByIdempotencyParams struct {
	SpaceID                  string
	EnrolledByUserID         string
	EnrollmentIdempotencyKey string
}

type FindEnrollmentByIdempotencyRow struct {
	MachineID      string
	SpaceID        string
	DisplayName    string
	CertificatePem []byte
	PublicKeyDer   []byte
}

func (q *Queries) FindEnrollmentByIdempotency(ctx context.Context, arg FindEnrollmentByIdempotencyParams) (FindEnrollmentByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findEnrollmentByIdempotency, arg.SpaceID, arg.EnrolledByUserID, arg.EnrollmentIdempotencyKey)
	var i FindEnrollmentByIdempotencyRow
	err := row.Scan(
		&i.MachineID,
		&i.SpaceID,
		&i.DisplayName,
		&i.CertificatePem,
		&i.PublicKeyDer,
	)
	return i, err
}

const revokeMachine = `-- name: RevokeMachine :execrows
UPDATE machines
SET revoked_at = coalesce(revoked_at, transaction_timestamp())
WHERE machine_id = $1
  AND space_id = $2
`

type RevokeMachineParams struct {
	MachineID string
	SpaceID   string
}

func (q *Queries) RevokeMachine(ctx context.Context, arg RevokeMachineParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMachine, arg.MachineID, arg.SpaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
