// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMachineEnrollmentPermission = `-- name: GetMachineEnrollmentPermission :one
SELECT can_enroll_machines
FROM space_memberships
WHERE
    space_id = $1
    AND user_id = $2
    AND revoked_at IS NULL
FOR SHARE
`

type GetMachineEnrollmentPermissionParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) GetMachineEnrollmentPermission(ctx context.Context, arg GetMachineEnrollmentPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, getMachineEnrollmentPermission, arg.SpaceID, arg.UserID)
	var can_enroll_machines bool
	err := row.Scan(&can_enroll_machines)
	return can_enroll_machines, err
}

const listActiveSpaceMembers = `-- name: ListActiveSpaceMembers :many
SELECT m.user_id, u.display_name, m.can_manage_members,
    m.can_enroll_machines, m.created_at AS joined_at
FROM space_memberships AS m
INNER JOIN carry_users AS u ON u.user_id = m.user_id
WHERE m.space_id = $1
    AND m.revoked_at IS NULL
ORDER BY m.created_at, m.user_id
LIMIT 100
`

type ListActiveSpaceMembersRow struct {
	UserID            string
	DisplayName       *string
	CanManageMembers  bool
	CanEnrollMachines bool
	JoinedAt          pgtype.Timestamptz
}

func (q *Queries) ListActiveSpaceMembers(ctx context.Context, spaceID string) ([]ListActiveSpaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSpaceMembersRow
	for rows.Next() {
		var i ListActiveSpaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.CanManageMembers,
			&i.CanEnrollMachines,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberships = `-- name: ListMemberships :many
SELECT
    m.space_id,
    s.name,
    m.can_manage_members,
    m.can_enroll_machines
FROM space_memberships AS m
INNER JOIN spaces AS s ON m.space_id = s.space_id
WHERE
    m.user_id = $1
    AND m.revoked_at IS NULL
ORDER BY s.name, m.space_id
`

type ListMembershipsRow struct {
	SpaceID           string
	Name              string
	CanManageMembers  bool
	CanEnrollMachines bool
}

func (q *Queries) ListMemberships(ctx context.Context, userID string) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsRow
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.SpaceID,
			&i.Name,
			&i.CanManageMembers,
			&i.CanEnrollMachines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
