// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BrowserSession struct {
	UserID              string
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
	SessionID           string
	IdentityProvedAt    pgtype.Timestamptz
	IdentityProofMethod string
}

type CarryUser struct {
	UserID      string
	DisplayName *string
	CreatedAt   pgtype.Timestamptz
}

type Conversation struct {
	ConversationID string
	SpaceID        string
	MemberUserID   string
	MessageHeadSeq int64
	CreatedAt      pgtype.Timestamptz
}

type ConversationMessage struct {
	MessageID              string
	ConversationID         string
	MessageSeq             int64
	Author                 string
	AuthorUserID           pgtype.UUID
	Text                   string
	MemberRequestID        *string
	RequestDigest          []byte
	ReplyToMemberMessageID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
}

type ConversationReplyClaim struct {
	SourceMessageID         string
	ConversationID          string
	SourceMessageAuthor     string
	CurrentMachineID        pgtype.UUID
	CurrentFence            int64
	LeaseExpiresAt          pgtype.Timestamptz
	ContextStartSeq         *int64
	ContextEndSeq           *int64
	OutputDigest            []byte
	CommittedReplyMessageID pgtype.UUID
	CommittedReplyAuthor    *string
	CreatedWorkID           pgtype.UUID
}

type EmailIdentity struct {
	CanonicalEmail string
	UserID         string
	VerifiedAt     pgtype.Timestamptz
}

type EmailLoginAttempt struct {
	ChallengeID    string
	IdempotencyKey string
	RequestDigest  []byte
	Result         string
	CreatedAt      pgtype.Timestamptz
}

type EmailLoginChallenge struct {
	ChallengeID           string
	CanonicalEmail        string
	CodeDigest            []byte
	SourceDigest          []byte
	PayloadDigest         []byte
	RequestIdempotencyKey string
	RequestDigest         []byte
	SubmissionState       string
	ProviderMessageID     *string
	AttemptsUsed          int32
	CreatedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	InvalidatedAt         pgtype.Timestamptz
	ConsumedAt            pgtype.Timestamptz
	UserID                pgtype.UUID
	BrowserSessionID      pgtype.UUID
	Purpose               string
	TargetUserID          pgtype.UUID
	InitiatingSessionID   pgtype.UUID
}

type ExternalLoginTransaction struct {
	TransactionID       string
	Provider            string
	Status              string
	CallbackDigest      []byte
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	UserID              pgtype.UUID
	BrowserSessionID    pgtype.UUID
	Purpose             string
	TargetUserID        pgtype.UUID
	InitiatingSessionID pgtype.UUID
}

type GithubIdentity struct {
	GithubUserID int64
	UserID       string
	VerifiedAt   pgtype.Timestamptz
}

type GoogleIdentity struct {
	Issuer     string
	Subject    string
	UserID     string
	VerifiedAt pgtype.Timestamptz
}

type IdentityMethodUnlink struct {
	UserID               string
	InitiatingSessionID  string
	Method               string
	IdempotencyKey       string
	RequestDigest        []byte
	ReplacementSessionID string
	CompletedAt          pgtype.Timestamptz
}

type Machine struct {
	MachineID                string
	SpaceID                  string
	DisplayName              string
	PublicKeyDer             []byte
	CertificatePem           []byte
	CertificateSerial        string
	EnrolledByUserID         string
	EnrollmentIdempotencyKey string
	EnrolledAt               pgtype.Timestamptz
	RevokedAt                pgtype.Timestamptz
}

type Run struct {
	RunID                    string
	WorkID                   string
	InputStartSeq            int64
	InputEndSeq              int64
	BaseUnderstandingVersion int64
	State                    string
	CurrentFence             int64
	CreatedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
	RetryRequestedAt         pgtype.Timestamptz
	RetryRequestedByUserID   pgtype.UUID
	RetryIdempotencyKey      *string
}

type RunAttempt struct {
	AttemptID      string
	RunID          string
	MachineID      string
	Fence          int64
	State          string
	LeaseExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type Space struct {
	SpaceID              string
	Name                 string
	CreatedAt            pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreateIdempotencyKey *string
	CreateRequestDigest  []byte
}

type SpaceInvitation struct {
	InvitationID         string
	SpaceID              string
	RecipientEmail       string
	InviterUserID        string
	CanManageMembers     bool
	CanEnrollMachines    bool
	IssueIdempotencyKey  string
	IssueRequestDigest   []byte
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	AcceptedByUserID     pgtype.UUID
	AcceptedAt           pgtype.Timestamptz
	AcceptResult         *string
	AcceptIdempotencyKey *string
	AcceptRequestDigest  []byte
	RevokedByUserID      pgtype.UUID
	RevokedAt            pgtype.Timestamptz
	RevokeIdempotencyKey *string
	RevokeRequestDigest  []byte
}

type SpaceInvitationSubmission struct {
	SubmissionID           string
	InvitationID           string
	RequestedByUserID      string
	IdempotencyKey         string
	RequestDigest          []byte
	RecipientEmail         string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	CreatedAt              pgtype.Timestamptz
	RecordedAt             pgtype.Timestamptz
}

type SpaceMembership struct {
	SpaceID                string
	UserID                 string
	CanEnrollMachines      bool
	Version                int64
	CreatedAt              pgtype.Timestamptz
	RevokedAt              pgtype.Timestamptz
	CanManageMembers       bool
	RemovedByUserID        pgtype.UUID
	RemovalSuccessorUserID pgtype.UUID
	RemovalIdempotencyKey  *string
	RemovalRequestDigest   []byte
}

type UserToken struct {
	TokenID   string
	UserID    string
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Work struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Lifecycle            string
	OwnerUserID          string
	CreatorUserID        string
	InputHeadSeq         int64
	CreateIdempotencyKey string
	CreateRequestDigest  []byte
	CreatedAt            pgtype.Timestamptz
	AppliedInputSeq      int64
	UnderstandingVersion int64
	Understanding        *string
	NextStep             *string
}

type WorkMessage struct {
	MessageID      string
	WorkID         string
	AuthorUserID   string
	Text           string
	InputSeq       int64
	IdempotencyKey string
	RequestDigest  []byte
	CreatedAt      pgtype.Timestamptz
}

type WorkResultCheck struct {
	ReviewID             string
	WorkID               string
	UnderstandingVersion int64
	ContentDigest        []byte
	RequestedAt          pgtype.Timestamptz
	AcceptedByUserID     pgtype.UUID
	AcceptIdempotencyKey *string
	AcceptRequestDigest  []byte
	AcceptedAt           pgtype.Timestamptz
}
