// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BrowserSession struct {
	SessionDigest []byte
	UserID        string
	SourceTokenID string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
}

type CarryUser struct {
	UserID      string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

type Machine struct {
	MachineID                string
	SpaceID                  string
	DisplayName              string
	PublicKeyDer             []byte
	CertificatePem           []byte
	CertificateSerial        string
	EnrolledByUserID         string
	EnrollmentIdempotencyKey string
	EnrolledAt               pgtype.Timestamptz
	RevokedAt                pgtype.Timestamptz
}

type Run struct {
	RunID                    string
	WorkID                   string
	InputStartSeq            int64
	InputEndSeq              int64
	BaseUnderstandingVersion int64
	State                    string
	CurrentFence             int64
	CreatedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
	RetryRequestedAt         pgtype.Timestamptz
	RetryRequestedByUserID   pgtype.UUID
	RetryIdempotencyKey      *string
}

type RunAttempt struct {
	AttemptID      string
	RunID          string
	MachineID      string
	Fence          int64
	State          string
	LeaseExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type Space struct {
	SpaceID   string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type SpaceMembership struct {
	SpaceID           string
	UserID            string
	CanEnrollMachines bool
	Version           int64
	CreatedAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type UserToken struct {
	TokenID   string
	UserID    string
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Work struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Lifecycle            string
	OwnerUserID          string
	CreatorUserID        string
	InputHeadSeq         int64
	CreateIdempotencyKey string
	CreateRequestDigest  []byte
	CreatedAt            pgtype.Timestamptz
	AppliedInputSeq      int64
	UnderstandingVersion int64
	Understanding        *string
	NextStep             *string
}

type WorkMessage struct {
	MessageID      string
	WorkID         string
	AuthorUserID   string
	Text           string
	InputSeq       int64
	IdempotencyKey string
	RequestDigest  []byte
	CreatedAt      pgtype.Timestamptz
}
