// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateCoordinatorRun = `-- name: ActivateCoordinatorRun :one
UPDATE coordinator_runs
SET state = 'active', current_fence = current_fence + 1
WHERE run_id = $1 AND state = 'pending'
RETURNING current_fence
`

func (q *Queries) ActivateCoordinatorRun(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, activateCoordinatorRun, runID)
	var current_fence int64
	err := row.Scan(&current_fence)
	return current_fence, err
}

const commitWorkRevision = `-- name: CommitWorkRevision :execrows
UPDATE works
SET
    applied_input_seq = $1,
    current_revision = $2
WHERE
    work_id = $3
    AND lifecycle = 'open'
    AND applied_input_seq = $4
    AND current_revision = $5
    AND input_head_seq >= $1
`

type CommitWorkRevisionParams struct {
	AppliedInputSeq         int64
	CurrentRevision         int64
	WorkID                  string
	ExpectedAppliedInputSeq int64
	ExpectedCurrentRevision int64
}

func (q *Queries) CommitWorkRevision(ctx context.Context, arg CommitWorkRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitWorkRevision,
		arg.AppliedInputSeq,
		arg.CurrentRevision,
		arg.WorkID,
		arg.ExpectedAppliedInputSeq,
		arg.ExpectedCurrentRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCoordinatorRun = `-- name: CreateCoordinatorRun :one
INSERT INTO coordinator_runs (
    run_id,
    work_id,
    input_start_seq,
    input_end_seq,
    base_revision,
    writer_token
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING run_id, work_id, input_start_seq, input_end_seq,
    base_revision, state, created_at
`

type CreateCoordinatorRunParams struct {
	RunID         string
	WorkID        string
	InputStartSeq int64
	InputEndSeq   int64
	BaseRevision  int64
	WriterToken   string
}

type CreateCoordinatorRunRow struct {
	RunID         string
	WorkID        string
	InputStartSeq int64
	InputEndSeq   int64
	BaseRevision  int64
	State         string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateCoordinatorRun(ctx context.Context, arg CreateCoordinatorRunParams) (CreateCoordinatorRunRow, error) {
	row := q.db.QueryRow(ctx, createCoordinatorRun,
		arg.RunID,
		arg.WorkID,
		arg.InputStartSeq,
		arg.InputEndSeq,
		arg.BaseRevision,
		arg.WriterToken,
	)
	var i CreateCoordinatorRunRow
	err := row.Scan(
		&i.RunID,
		&i.WorkID,
		&i.InputStartSeq,
		&i.InputEndSeq,
		&i.BaseRevision,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const createRunAttempt = `-- name: CreateRunAttempt :one
INSERT INTO run_attempts (
    attempt_id,
    run_id,
    machine_id,
    fence,
    agent_credential_digest,
    lease_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    transaction_timestamp() + interval '5 minutes'
)
RETURNING attempt_id, fence, lease_expires_at
`

type CreateRunAttemptParams struct {
	AttemptID             string
	RunID                 string
	MachineID             string
	Fence                 int64
	AgentCredentialDigest []byte
}

type CreateRunAttemptRow struct {
	AttemptID      string
	Fence          int64
	LeaseExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRunAttempt(ctx context.Context, arg CreateRunAttemptParams) (CreateRunAttemptRow, error) {
	row := q.db.QueryRow(ctx, createRunAttempt,
		arg.AttemptID,
		arg.RunID,
		arg.MachineID,
		arg.Fence,
		arg.AgentCredentialDigest,
	)
	var i CreateRunAttemptRow
	err := row.Scan(&i.AttemptID, &i.Fence, &i.LeaseExpiresAt)
	return i, err
}

const createWorkUnderstandingRevision = `-- name: CreateWorkUnderstandingRevision :exec
INSERT INTO work_understanding_revisions (
    work_id,
    revision,
    source_run_id,
    understanding,
    next_step,
    applied_input_seq
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateWorkUnderstandingRevisionParams struct {
	WorkID          string
	Revision        int64
	SourceRunID     string
	Understanding   string
	NextStep        string
	AppliedInputSeq int64
}

func (q *Queries) CreateWorkUnderstandingRevision(ctx context.Context, arg CreateWorkUnderstandingRevisionParams) error {
	_, err := q.db.Exec(ctx, createWorkUnderstandingRevision,
		arg.WorkID,
		arg.Revision,
		arg.SourceRunID,
		arg.Understanding,
		arg.NextStep,
		arg.AppliedInputSeq,
	)
	return err
}

const extendRunAttemptLease = `-- name: ExtendRunAttemptLease :one
WITH current_machine AS (
    SELECT machines.machine_id
    FROM machines
    WHERE machines.machine_id = $4 AND machines.revoked_at IS NULL
    FOR SHARE OF machines
)
UPDATE run_attempts AS attempt
SET lease_expires_at = transaction_timestamp() + interval '5 minutes'
FROM coordinator_runs AS coordinator, current_machine
WHERE
    attempt.attempt_id = $1
    AND attempt.run_id = $2
    AND attempt.machine_id = current_machine.machine_id
    AND attempt.fence = $3
    AND attempt.state = 'active'
    AND coordinator.run_id = attempt.run_id
    AND coordinator.current_fence = attempt.fence
    AND coordinator.state = 'active'
RETURNING attempt.lease_expires_at
`

type ExtendRunAttemptLeaseParams struct {
	AttemptID         string
	RunID             string
	Fence             int64
	ClaimingMachineID string
}

func (q *Queries) ExtendRunAttemptLease(ctx context.Context, arg ExtendRunAttemptLeaseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, extendRunAttemptLease,
		arg.AttemptID,
		arg.RunID,
		arg.Fence,
		arg.ClaimingMachineID,
	)
	var lease_expires_at pgtype.Timestamptz
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const finishUnresolvedCoordinatorRun = `-- name: FinishUnresolvedCoordinatorRun :execrows
UPDATE coordinator_runs
SET state = $1
WHERE run_id = $2 AND state = 'active'
`

type FinishUnresolvedCoordinatorRunParams struct {
	Outcome string
	RunID   string
}

func (q *Queries) FinishUnresolvedCoordinatorRun(ctx context.Context, arg FinishUnresolvedCoordinatorRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishUnresolvedCoordinatorRun, arg.Outcome, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishUnresolvedRunAttempt = `-- name: FinishUnresolvedRunAttempt :execrows
UPDATE run_attempts
SET state = $1, completed_at = transaction_timestamp()
WHERE attempt_id = $2 AND state = 'active'
`

type FinishUnresolvedRunAttemptParams struct {
	Outcome   string
	AttemptID string
}

func (q *Queries) FinishUnresolvedRunAttempt(ctx context.Context, arg FinishUnresolvedRunAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishUnresolvedRunAttempt, arg.Outcome, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRunInputMessages = `-- name: ListRunInputMessages :many
SELECT message_id, author_user_id, text, input_seq, created_at
FROM work_messages
WHERE
    work_id = $1
    AND input_seq >= $2
    AND input_seq <= $3
ORDER BY input_seq
`

type ListRunInputMessagesParams struct {
	WorkID        string
	InputStartSeq int64
	InputEndSeq   int64
}

type ListRunInputMessagesRow struct {
	MessageID    string
	AuthorUserID string
	Text         string
	InputSeq     int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListRunInputMessages(ctx context.Context, arg ListRunInputMessagesParams) ([]ListRunInputMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRunInputMessages, arg.WorkID, arg.InputStartSeq, arg.InputEndSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunInputMessagesRow
	for rows.Next() {
		var i ListRunInputMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.AuthorUserID,
			&i.Text,
			&i.InputSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadActiveAttemptContext = `-- name: LoadActiveAttemptContext :one
SELECT
    r.run_id,
    a.attempt_id,
    r.work_id,
    w.space_id,
    w.goal,
    revision.understanding AS current_understanding,
    revision.next_step AS current_next_step,
    r.input_start_seq,
    r.input_end_seq,
    r.base_revision,
    a.fence
FROM coordinator_runs AS r
JOIN run_attempts AS a ON a.run_id = r.run_id
JOIN works AS w ON w.work_id = r.work_id
LEFT JOIN work_understanding_revisions AS revision
    ON revision.work_id = r.work_id AND revision.revision = r.base_revision
JOIN machines AS m ON m.machine_id = a.machine_id AND m.revoked_at IS NULL
WHERE
    r.run_id = $1
    AND a.attempt_id = $2
    AND a.fence = $3
    AND a.agent_credential_digest = $4
    AND r.state = 'active'
    AND a.state = 'active'
    AND a.lease_expires_at > transaction_timestamp()
`

type LoadActiveAttemptContextParams struct {
	RunID                 string
	AttemptID             string
	Fence                 int64
	AgentCredentialDigest []byte
}

type LoadActiveAttemptContextRow struct {
	RunID                string
	AttemptID            string
	WorkID               string
	SpaceID              string
	Goal                 string
	CurrentUnderstanding *string
	CurrentNextStep      *string
	InputStartSeq        int64
	InputEndSeq          int64
	BaseRevision         int64
	Fence                int64
}

func (q *Queries) LoadActiveAttemptContext(ctx context.Context, arg LoadActiveAttemptContextParams) (LoadActiveAttemptContextRow, error) {
	row := q.db.QueryRow(ctx, loadActiveAttemptContext,
		arg.RunID,
		arg.AttemptID,
		arg.Fence,
		arg.AgentCredentialDigest,
	)
	var i LoadActiveAttemptContextRow
	err := row.Scan(
		&i.RunID,
		&i.AttemptID,
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.CurrentUnderstanding,
		&i.CurrentNextStep,
		&i.InputStartSeq,
		&i.InputEndSeq,
		&i.BaseRevision,
		&i.Fence,
	)
	return i, err
}

const lockAttemptForCommit = `-- name: LockAttemptForCommit :one
SELECT
    r.work_id,
    r.input_start_seq,
    r.input_end_seq,
    r.base_revision,
    w.applied_input_seq,
    w.input_head_seq,
    w.current_revision,
    w.lifecycle
FROM coordinator_runs AS r
JOIN run_attempts AS a ON a.run_id = r.run_id
JOIN works AS w ON w.work_id = r.work_id
JOIN machines AS m ON m.machine_id = a.machine_id AND m.revoked_at IS NULL
WHERE
    r.run_id = $1
    AND a.attempt_id = $2
    AND a.fence = $3
    AND r.current_fence = $3
    AND r.writer_token = $4
    AND a.agent_credential_digest = $5
    AND r.state = 'active'
    AND a.state = 'active'
    AND a.lease_expires_at > transaction_timestamp()
FOR UPDATE OF r, a, w
FOR SHARE OF m
`

type LockAttemptForCommitParams struct {
	RunID                 string
	AttemptID             string
	Fence                 int64
	WriterToken           string
	AgentCredentialDigest []byte
}

type LockAttemptForCommitRow struct {
	WorkID          string
	InputStartSeq   int64
	InputEndSeq     int64
	BaseRevision    int64
	AppliedInputSeq int64
	InputHeadSeq    int64
	CurrentRevision int64
	Lifecycle       string
}

func (q *Queries) LockAttemptForCommit(ctx context.Context, arg LockAttemptForCommitParams) (LockAttemptForCommitRow, error) {
	row := q.db.QueryRow(ctx, lockAttemptForCommit,
		arg.RunID,
		arg.AttemptID,
		arg.Fence,
		arg.WriterToken,
		arg.AgentCredentialDigest,
	)
	var i LockAttemptForCommitRow
	err := row.Scan(
		&i.WorkID,
		&i.InputStartSeq,
		&i.InputEndSeq,
		&i.BaseRevision,
		&i.AppliedInputSeq,
		&i.InputHeadSeq,
		&i.CurrentRevision,
		&i.Lifecycle,
	)
	return i, err
}

const lockClaimingMachine = `-- name: LockClaimingMachine :one
SELECT space_id, revoked_at
FROM machines
WHERE machine_id = $1
FOR SHARE
`

type LockClaimingMachineRow struct {
	SpaceID   string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) LockClaimingMachine(ctx context.Context, machineID string) (LockClaimingMachineRow, error) {
	row := q.db.QueryRow(ctx, lockClaimingMachine, machineID)
	var i LockClaimingMachineRow
	err := row.Scan(&i.SpaceID, &i.RevokedAt)
	return i, err
}

const lockPendingCoordinatorRun = `-- name: LockPendingCoordinatorRun :one
SELECT r.run_id, r.work_id, w.space_id, r.input_start_seq, r.input_end_seq,
    r.base_revision, r.writer_token, r.current_fence, r.created_at
FROM coordinator_runs AS r
JOIN works AS w ON w.work_id = r.work_id
WHERE w.space_id = $1 AND r.state = 'pending'
ORDER BY r.created_at, r.run_id
LIMIT 1
FOR UPDATE OF r SKIP LOCKED
`

type LockPendingCoordinatorRunRow struct {
	RunID         string
	WorkID        string
	SpaceID       string
	InputStartSeq int64
	InputEndSeq   int64
	BaseRevision  int64
	WriterToken   string
	CurrentFence  int64
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) LockPendingCoordinatorRun(ctx context.Context, spaceID string) (LockPendingCoordinatorRunRow, error) {
	row := q.db.QueryRow(ctx, lockPendingCoordinatorRun, spaceID)
	var i LockPendingCoordinatorRunRow
	err := row.Scan(
		&i.RunID,
		&i.WorkID,
		&i.SpaceID,
		&i.InputStartSeq,
		&i.InputEndSeq,
		&i.BaseRevision,
		&i.WriterToken,
		&i.CurrentFence,
		&i.CreatedAt,
	)
	return i, err
}

const lockWorkForCoordination = `-- name: LockWorkForCoordination :one
SELECT
    w.work_id,
    w.space_id,
    w.applied_input_seq,
    w.input_head_seq,
    w.current_revision
FROM works AS w
WHERE
    w.lifecycle = 'open'
    AND w.applied_input_seq < w.input_head_seq
    AND NOT EXISTS (
        SELECT 1
        FROM coordinator_runs AS r
        WHERE r.work_id = w.work_id
          AND r.state IN ('pending', 'active', 'failed', 'unknown')
    )
ORDER BY w.created_at, w.work_id
LIMIT 1
FOR UPDATE OF w SKIP LOCKED
`

type LockWorkForCoordinationRow struct {
	WorkID          string
	SpaceID         string
	AppliedInputSeq int64
	InputHeadSeq    int64
	CurrentRevision int64
}

func (q *Queries) LockWorkForCoordination(ctx context.Context) (LockWorkForCoordinationRow, error) {
	row := q.db.QueryRow(ctx, lockWorkForCoordination)
	var i LockWorkForCoordinationRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.AppliedInputSeq,
		&i.InputHeadSeq,
		&i.CurrentRevision,
	)
	return i, err
}

const succeedCoordinatorRun = `-- name: SucceedCoordinatorRun :execrows
UPDATE coordinator_runs
SET state = 'succeeded', completed_at = transaction_timestamp()
WHERE run_id = $1 AND state = 'active'
`

func (q *Queries) SucceedCoordinatorRun(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.Exec(ctx, succeedCoordinatorRun, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedRunAttempt = `-- name: SucceedRunAttempt :execrows
UPDATE run_attempts
SET state = 'succeeded', completed_at = transaction_timestamp()
WHERE attempt_id = $1 AND state = 'active'
`

func (q *Queries) SucceedRunAttempt(ctx context.Context, attemptID string) (int64, error) {
	result, err := q.db.Exec(ctx, succeedRunAttempt, attemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
