// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitCurrentUnderstanding = `-- name: CommitCurrentUnderstanding :execrows
UPDATE works
SET
    understanding = $1,
    next_step = $2,
    applied_input_seq = $3,
    understanding_version = understanding_version + 1
WHERE
    work_id = $4
    AND lifecycle = 'open'
    AND applied_input_seq = $5
    AND understanding_version = $6
    AND input_head_seq >= $3
`

type CommitCurrentUnderstandingParams struct {
	Understanding                *string
	NextStep                     *string
	AppliedInputSeq              int64
	WorkID                       string
	ExpectedAppliedInputSeq      int64
	ExpectedUnderstandingVersion int64
}

func (q *Queries) CommitCurrentUnderstanding(ctx context.Context, arg CommitCurrentUnderstandingParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitCurrentUnderstanding,
		arg.Understanding,
		arg.NextStep,
		arg.AppliedInputSeq,
		arg.WorkID,
		arg.ExpectedAppliedInputSeq,
		arg.ExpectedUnderstandingVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (
    run_id,
    work_id,
    input_start_seq,
    input_end_seq,
    base_understanding_version,
    state,
    current_fence
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'active',
    1
)
RETURNING created_at
`

type CreateRunParams struct {
	RunID                    string
	WorkID                   string
	InputStartSeq            int64
	InputEndSeq              int64
	BaseUnderstandingVersion int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.RunID,
		arg.WorkID,
		arg.InputStartSeq,
		arg.InputEndSeq,
		arg.BaseUnderstandingVersion,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const createRunAttempt = `-- name: CreateRunAttempt :one
INSERT INTO run_attempts (
    attempt_id,
    run_id,
    machine_id,
    fence,
    lease_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    clock_timestamp() + interval '5 minutes'
)
RETURNING lease_expires_at
`

type CreateRunAttemptParams struct {
	AttemptID string
	RunID     string
	MachineID string
	Fence     int64
}

func (q *Queries) CreateRunAttempt(ctx context.Context, arg CreateRunAttemptParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createRunAttempt,
		arg.AttemptID,
		arg.RunID,
		arg.MachineID,
		arg.Fence,
	)
	var lease_expires_at pgtype.Timestamptz
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const expireRunAttempt = `-- name: ExpireRunAttempt :execrows
UPDATE run_attempts
SET state = 'expired', completed_at = clock_timestamp()
WHERE
    attempt_id = $1
    AND run_id = $2
    AND fence = $3
    AND state = 'active'
    AND lease_expires_at <= clock_timestamp()
`

type ExpireRunAttemptParams struct {
	AttemptID string
	RunID     string
	Fence     int64
}

func (q *Queries) ExpireRunAttempt(ctx context.Context, arg ExpireRunAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireRunAttempt, arg.AttemptID, arg.RunID, arg.Fence)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendRunAttemptLease = `-- name: ExtendRunAttemptLease :one
WITH current_machine AS (
    SELECT machines.machine_id
    FROM machines
    WHERE machines.machine_id = $4 AND machines.revoked_at IS NULL
    FOR SHARE
)
UPDATE run_attempts AS attempt
SET lease_expires_at = clock_timestamp() + interval '5 minutes'
FROM runs AS run, current_machine
WHERE
    attempt.attempt_id = $1
    AND attempt.run_id = $2
    AND attempt.machine_id = current_machine.machine_id
    AND attempt.fence = $3
    AND attempt.state = 'active'
    AND attempt.lease_expires_at > clock_timestamp()
    AND run.run_id = attempt.run_id
    AND run.current_fence = attempt.fence
    AND run.state = 'active'
RETURNING attempt.lease_expires_at
`

type ExtendRunAttemptLeaseParams struct {
	AttemptID         string
	RunID             string
	Fence             int64
	ClaimingMachineID string
}

func (q *Queries) ExtendRunAttemptLease(ctx context.Context, arg ExtendRunAttemptLeaseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, extendRunAttemptLease,
		arg.AttemptID,
		arg.RunID,
		arg.Fence,
		arg.ClaimingMachineID,
	)
	var lease_expires_at pgtype.Timestamptz
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const findRunRetryByIdempotency = `-- name: FindRunRetryByIdempotency :one
SELECT retry_requested_by_user_id::text
FROM runs
WHERE work_id = $1
  AND retry_idempotency_key = $2::text
`

type FindRunRetryByIdempotencyParams struct {
	WorkID              string
	RetryIdempotencyKey string
}

func (q *Queries) FindRunRetryByIdempotency(ctx context.Context, arg FindRunRetryByIdempotencyParams) (string, error) {
	row := q.db.QueryRow(ctx, findRunRetryByIdempotency, arg.WorkID, arg.RetryIdempotencyKey)
	var retry_requested_by_user_id string
	err := row.Scan(&retry_requested_by_user_id)
	return retry_requested_by_user_id, err
}

const finishRun = `-- name: FinishRun :execrows
UPDATE runs
SET state = $1, completed_at = clock_timestamp()
WHERE run_id = $2 AND state = 'active'
`

type FinishRunParams struct {
	Outcome string
	RunID   string
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRun, arg.Outcome, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRunAttempt = `-- name: FinishRunAttempt :execrows
UPDATE run_attempts
SET state = $1, completed_at = clock_timestamp()
WHERE attempt_id = $2 AND state = 'active'
`

type FinishRunAttemptParams struct {
	Outcome   string
	AttemptID string
}

func (q *Queries) FinishRunAttempt(ctx context.Context, arg FinishRunAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRunAttempt, arg.Outcome, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRunInputMessages = `-- name: ListRunInputMessages :many
SELECT author_user_id, text
FROM work_messages
WHERE
    work_id = $1
    AND input_seq >= $2
    AND input_seq <= $3
ORDER BY input_seq
`

type ListRunInputMessagesParams struct {
	WorkID        string
	InputStartSeq int64
	InputEndSeq   int64
}

type ListRunInputMessagesRow struct {
	AuthorUserID string
	Text         string
}

func (q *Queries) ListRunInputMessages(ctx context.Context, arg ListRunInputMessagesParams) ([]ListRunInputMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRunInputMessages, arg.WorkID, arg.InputStartSeq, arg.InputEndSeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunInputMessagesRow
	for rows.Next() {
		var i ListRunInputMessagesRow
		if err := rows.Scan(&i.AuthorUserID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttemptForCommit = `-- name: LockAttemptForCommit :one
SELECT
    run.work_id,
    run.input_start_seq,
    run.input_end_seq,
    run.base_understanding_version,
    work.applied_input_seq,
    work.input_head_seq,
    work.understanding_version,
    work.lifecycle
FROM runs AS run
JOIN run_attempts AS attempt ON attempt.run_id = run.run_id
JOIN works AS work ON work.work_id = run.work_id
JOIN machines AS machine ON machine.machine_id = attempt.machine_id
WHERE
    run.run_id = $1
    AND attempt.attempt_id = $2
    AND attempt.machine_id = $3
    AND attempt.fence = $4
    AND run.current_fence = attempt.fence
    AND run.state = 'active'
    AND attempt.state = 'active'
    AND machine.revoked_at IS NULL
FOR UPDATE OF run, attempt, work
FOR SHARE OF machine
`

type LockAttemptForCommitParams struct {
	RunID             string
	AttemptID         string
	ClaimingMachineID string
	Fence             int64
}

type LockAttemptForCommitRow struct {
	WorkID                   string
	InputStartSeq            int64
	InputEndSeq              int64
	BaseUnderstandingVersion int64
	AppliedInputSeq          int64
	InputHeadSeq             int64
	UnderstandingVersion     int64
	Lifecycle                string
}

func (q *Queries) LockAttemptForCommit(ctx context.Context, arg LockAttemptForCommitParams) (LockAttemptForCommitRow, error) {
	row := q.db.QueryRow(ctx, lockAttemptForCommit,
		arg.RunID,
		arg.AttemptID,
		arg.ClaimingMachineID,
		arg.Fence,
	)
	var i LockAttemptForCommitRow
	err := row.Scan(
		&i.WorkID,
		&i.InputStartSeq,
		&i.InputEndSeq,
		&i.BaseUnderstandingVersion,
		&i.AppliedInputSeq,
		&i.InputHeadSeq,
		&i.UnderstandingVersion,
		&i.Lifecycle,
	)
	return i, err
}

const lockAttemptForFinish = `-- name: LockAttemptForFinish :one
SELECT run.run_id
FROM runs AS run
JOIN run_attempts AS attempt ON attempt.run_id = run.run_id
JOIN machines AS machine ON machine.machine_id = attempt.machine_id
WHERE
    run.run_id = $1
    AND attempt.attempt_id = $2
    AND attempt.machine_id = $3
    AND attempt.fence = $4
    AND run.current_fence = attempt.fence
    AND run.state = 'active'
    AND attempt.state = 'active'
    AND machine.revoked_at IS NULL
FOR UPDATE OF run, attempt
FOR SHARE OF machine
`

type LockAttemptForFinishParams struct {
	RunID             string
	AttemptID         string
	ClaimingMachineID string
	Fence             int64
}

func (q *Queries) LockAttemptForFinish(ctx context.Context, arg LockAttemptForFinishParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAttemptForFinish,
		arg.RunID,
		arg.AttemptID,
		arg.ClaimingMachineID,
		arg.Fence,
	)
	var run_id string
	err := row.Scan(&run_id)
	return run_id, err
}

const lockAttemptForRenew = `-- name: LockAttemptForRenew :one
SELECT attempt.attempt_id
FROM run_attempts AS attempt
JOIN runs AS run ON run.run_id = attempt.run_id
JOIN machines AS machine ON machine.machine_id = attempt.machine_id
WHERE
    run.run_id = $1
    AND attempt.attempt_id = $2
    AND attempt.machine_id = $3
    AND attempt.fence = $4
    AND run.current_fence = attempt.fence
    AND run.state = 'active'
    AND attempt.state = 'active'
    AND machine.revoked_at IS NULL
FOR UPDATE OF run, attempt
FOR SHARE OF machine
`

type LockAttemptForRenewParams struct {
	RunID             string
	AttemptID         string
	ClaimingMachineID string
	Fence             int64
}

func (q *Queries) LockAttemptForRenew(ctx context.Context, arg LockAttemptForRenewParams) (string, error) {
	row := q.db.QueryRow(ctx, lockAttemptForRenew,
		arg.RunID,
		arg.AttemptID,
		arg.ClaimingMachineID,
		arg.Fence,
	)
	var attempt_id string
	err := row.Scan(&attempt_id)
	return attempt_id, err
}

const lockClaimingMachine = `-- name: LockClaimingMachine :one
SELECT space_id, revoked_at
FROM machines
WHERE machine_id = $1
FOR SHARE
`

type LockClaimingMachineRow struct {
	SpaceID   string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) LockClaimingMachine(ctx context.Context, machineID string) (LockClaimingMachineRow, error) {
	row := q.db.QueryRow(ctx, lockClaimingMachine, machineID)
	var i LockClaimingMachineRow
	err := row.Scan(&i.SpaceID, &i.RevokedAt)
	return i, err
}

const lockExpiredRunForClaim = `-- name: LockExpiredRunForClaim :one
SELECT
    run.run_id,
    run.work_id,
    work.space_id,
    work.goal,
    work.understanding,
    work.next_step,
    run.input_start_seq,
    run.input_end_seq,
    run.base_understanding_version,
    run.current_fence,
    attempt.attempt_id AS expired_attempt_id
FROM runs AS run
JOIN works AS work ON work.work_id = run.work_id
JOIN run_attempts AS attempt
    ON attempt.run_id = run.run_id AND attempt.fence = run.current_fence
WHERE
    work.space_id = $1
    AND work.lifecycle = 'open'
    AND run.state = 'active'
    AND attempt.state = 'active'
    AND attempt.lease_expires_at <= clock_timestamp()
ORDER BY attempt.lease_expires_at, run.created_at, run.run_id
LIMIT 1
FOR UPDATE OF run, attempt, work SKIP LOCKED
`

type LockExpiredRunForClaimRow struct {
	RunID                    string
	WorkID                   string
	SpaceID                  string
	Goal                     string
	Understanding            *string
	NextStep                 *string
	InputStartSeq            int64
	InputEndSeq              int64
	BaseUnderstandingVersion int64
	CurrentFence             int64
	ExpiredAttemptID         string
}

func (q *Queries) LockExpiredRunForClaim(ctx context.Context, spaceID string) (LockExpiredRunForClaimRow, error) {
	row := q.db.QueryRow(ctx, lockExpiredRunForClaim, spaceID)
	var i LockExpiredRunForClaimRow
	err := row.Scan(
		&i.RunID,
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Understanding,
		&i.NextStep,
		&i.InputStartSeq,
		&i.InputEndSeq,
		&i.BaseUnderstandingVersion,
		&i.CurrentFence,
		&i.ExpiredAttemptID,
	)
	return i, err
}

const lockRetryableRun = `-- name: LockRetryableRun :one
SELECT run_id
FROM runs
WHERE work_id = $1
  AND state IN ('failed', 'unknown')
  AND retry_requested_at IS NULL
ORDER BY completed_at DESC, run_id DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockRetryableRun(ctx context.Context, workID string) (string, error) {
	row := q.db.QueryRow(ctx, lockRetryableRun, workID)
	var run_id string
	err := row.Scan(&run_id)
	return run_id, err
}

const lockWorkForRetry = `-- name: LockWorkForRetry :one
SELECT lifecycle
FROM works
WHERE work_id = $1 AND space_id = $2
FOR UPDATE
`

type LockWorkForRetryParams struct {
	WorkID  string
	SpaceID string
}

func (q *Queries) LockWorkForRetry(ctx context.Context, arg LockWorkForRetryParams) (string, error) {
	row := q.db.QueryRow(ctx, lockWorkForRetry, arg.WorkID, arg.SpaceID)
	var lifecycle string
	err := row.Scan(&lifecycle)
	return lifecycle, err
}

const lockWorkForRunClaim = `-- name: LockWorkForRunClaim :one
SELECT
    work.work_id,
    work.space_id,
    work.goal,
    work.understanding,
    work.next_step,
    work.applied_input_seq,
    work.input_head_seq,
    work.understanding_version
FROM works AS work
WHERE
    work.space_id = $1
    AND work.lifecycle = 'open'
    AND work.applied_input_seq < work.input_head_seq
    AND NOT EXISTS (
        SELECT 1
        FROM runs AS run
        WHERE run.work_id = work.work_id
          AND (
              run.state = 'active'
              OR (run.state IN ('failed', 'unknown') AND run.retry_requested_at IS NULL)
          )
    )
ORDER BY work.created_at, work.work_id
LIMIT 1
FOR UPDATE OF work SKIP LOCKED
`

type LockWorkForRunClaimRow struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Understanding        *string
	NextStep             *string
	AppliedInputSeq      int64
	InputHeadSeq         int64
	UnderstandingVersion int64
}

func (q *Queries) LockWorkForRunClaim(ctx context.Context, spaceID string) (LockWorkForRunClaimRow, error) {
	row := q.db.QueryRow(ctx, lockWorkForRunClaim, spaceID)
	var i LockWorkForRunClaimRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Understanding,
		&i.NextStep,
		&i.AppliedInputSeq,
		&i.InputHeadSeq,
		&i.UnderstandingVersion,
	)
	return i, err
}

const requestRunRetry = `-- name: RequestRunRetry :execrows
UPDATE runs
SET
    retry_requested_at = clock_timestamp(),
    retry_requested_by_user_id = $1::uuid,
    retry_idempotency_key = $2::text
WHERE run_id = $3
  AND state IN ('failed', 'unknown')
  AND retry_requested_at IS NULL
`

type RequestRunRetryParams struct {
	RequestedByUserID   string
	RetryIdempotencyKey string
	RunID               string
}

func (q *Queries) RequestRunRetry(ctx context.Context, arg RequestRunRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestRunRetry, arg.RequestedByUserID, arg.RetryIdempotencyKey, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRunFence = `-- name: RotateRunFence :one
UPDATE runs
SET current_fence = current_fence + 1
WHERE
    run_id = $1
    AND state = 'active'
    AND current_fence = $2
RETURNING current_fence
`

type RotateRunFenceParams struct {
	RunID        string
	CurrentFence int64
}

func (q *Queries) RotateRunFence(ctx context.Context, arg RotateRunFenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, rotateRunFence, arg.RunID, arg.CurrentFence)
	var current_fence int64
	err := row.Scan(&current_fence)
	return current_fence, err
}

const runAttemptLeaseIsCurrent = `-- name: RunAttemptLeaseIsCurrent :one
SELECT lease_expires_at > clock_timestamp()
FROM run_attempts
WHERE attempt_id = $1
`

func (q *Queries) RunAttemptLeaseIsCurrent(ctx context.Context, attemptID string) (bool, error) {
	row := q.db.QueryRow(ctx, runAttemptLeaseIsCurrent, attemptID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const selectRunInputEnd = `-- name: SelectRunInputEnd :one
WITH upcoming AS (
    SELECT input_seq, text
    FROM work_messages
    WHERE
        work_id = $2
        AND input_seq >= $1
        AND input_seq <= $3
    ORDER BY input_seq
    LIMIT 32
), candidates AS (
    SELECT
        input_seq,
        sum(octet_length(text)) OVER (
            ORDER BY input_seq ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS text_bytes
    FROM upcoming
)
SELECT coalesce(max(input_seq), $1)::bigint
FROM candidates
WHERE text_bytes <= 262144
`

type SelectRunInputEndParams struct {
	InputStartSeq int64
	WorkID        string
	InputHeadSeq  int64
}

func (q *Queries) SelectRunInputEnd(ctx context.Context, arg SelectRunInputEndParams) (int64, error) {
	row := q.db.QueryRow(ctx, selectRunInputEnd, arg.InputStartSeq, arg.WorkID, arg.InputHeadSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const succeedRun = `-- name: SucceedRun :execrows
UPDATE runs
SET state = 'succeeded', completed_at = clock_timestamp()
WHERE run_id = $1 AND state = 'active'
`

func (q *Queries) SucceedRun(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.Exec(ctx, succeedRun, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedRunAttempt = `-- name: SucceedRunAttempt :execrows
UPDATE run_attempts
SET state = 'succeeded', completed_at = clock_timestamp()
WHERE attempt_id = $1 AND state = 'active'
`

func (q *Queries) SucceedRunAttempt(ctx context.Context, attemptID string) (int64, error) {
	result, err := q.db.Exec(ctx, succeedRunAttempt, attemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
