// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_invitation.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptSpaceInvitation = `-- name: AcceptSpaceInvitation :execrows
UPDATE space_invitations
SET
    accepted_by_user_id = $1,
    accepted_at = transaction_timestamp(),
    accept_result = $2,
    accept_idempotency_key = $3,
    accept_request_digest = $4
WHERE invitation_id = $5
    AND accepted_at IS NULL
    AND revoked_at IS NULL
    AND expires_at > transaction_timestamp()
`

type AcceptSpaceInvitationParams struct {
	UserID         pgtype.UUID
	AcceptResult   *string
	IdempotencyKey *string
	RequestDigest  []byte
	InvitationID   string
}

func (q *Queries) AcceptSpaceInvitation(ctx context.Context, arg AcceptSpaceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptSpaceInvitation,
		arg.UserID,
		arg.AcceptResult,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.InvitationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvitationMembership = `-- name: CreateInvitationMembership :exec
INSERT INTO space_memberships (
    space_id, user_id, can_manage_members, can_enroll_machines
) VALUES (
    $1, $2,
    $3, $4
)
`

type CreateInvitationMembershipParams struct {
	SpaceID           string
	UserID            string
	CanManageMembers  bool
	CanEnrollMachines bool
}

func (q *Queries) CreateInvitationMembership(ctx context.Context, arg CreateInvitationMembershipParams) error {
	_, err := q.db.Exec(ctx, createInvitationMembership,
		arg.SpaceID,
		arg.UserID,
		arg.CanManageMembers,
		arg.CanEnrollMachines,
	)
	return err
}

const emailOwnerIsActiveSpaceMember = `-- name: EmailOwnerIsActiveSpaceMember :one
SELECT exists(
    SELECT 1
    FROM email_identities AS e
    INNER JOIN space_memberships AS m ON m.user_id = e.user_id
    WHERE e.canonical_email = $1
        AND m.space_id = $2
        AND m.revoked_at IS NULL
)
`

type EmailOwnerIsActiveSpaceMemberParams struct {
	RecipientEmail string
	SpaceID        string
}

func (q *Queries) EmailOwnerIsActiveSpaceMember(ctx context.Context, arg EmailOwnerIsActiveSpaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailOwnerIsActiveSpaceMember, arg.RecipientEmail, arg.SpaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasCurrentSpaceInvitation = `-- name: HasCurrentSpaceInvitation :one
SELECT exists(
    SELECT 1 FROM space_invitations
    WHERE space_id = $1
        AND recipient_email = $2
        AND accepted_at IS NULL
        AND revoked_at IS NULL
        AND expires_at > transaction_timestamp()
)
`

type HasCurrentSpaceInvitationParams struct {
	SpaceID        string
	RecipientEmail string
}

func (q *Queries) HasCurrentSpaceInvitation(ctx context.Context, arg HasCurrentSpaceInvitationParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCurrentSpaceInvitation, arg.SpaceID, arg.RecipientEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertSpaceInvitation = `-- name: InsertSpaceInvitation :one
INSERT INTO space_invitations (
    invitation_id, space_id, recipient_email, inviter_user_id,
    can_manage_members, can_enroll_machines,
    issue_idempotency_key, issue_request_digest
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING created_at, expires_at
`

type InsertSpaceInvitationParams struct {
	InvitationID      string
	SpaceID           string
	RecipientEmail    string
	UserID            string
	CanManageMembers  bool
	CanEnrollMachines bool
	IdempotencyKey    string
	RequestDigest     []byte
}

type InsertSpaceInvitationRow struct {
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSpaceInvitation(ctx context.Context, arg InsertSpaceInvitationParams) (InsertSpaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, insertSpaceInvitation,
		arg.InvitationID,
		arg.SpaceID,
		arg.RecipientEmail,
		arg.UserID,
		arg.CanManageMembers,
		arg.CanEnrollMachines,
		arg.IdempotencyKey,
		arg.RequestDigest,
	)
	var i InsertSpaceInvitationRow
	err := row.Scan(&i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const insertSpaceInvitationSubmission = `-- name: InsertSpaceInvitationSubmission :one
INSERT INTO space_invitation_submissions (
    submission_id, invitation_id, requested_by_user_id,
    idempotency_key, request_digest, recipient_email,
    payload_digest, provider_idempotency_key
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
RETURNING submission_id, recipient_email, payload_digest,
    provider_idempotency_key, state, provider_message_id, created_at,
    (state = 'prepared' AND created_at + interval '24 hours' > transaction_timestamp()) AS submit_eligible
`

type InsertSpaceInvitationSubmissionParams struct {
	SubmissionID           string
	InvitationID           string
	UserID                 string
	IdempotencyKey         string
	RequestDigest          []byte
	RecipientEmail         string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
}

type InsertSpaceInvitationSubmissionRow struct {
	SubmissionID           string
	RecipientEmail         string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	CreatedAt              pgtype.Timestamptz
	SubmitEligible         *bool
}

func (q *Queries) InsertSpaceInvitationSubmission(ctx context.Context, arg InsertSpaceInvitationSubmissionParams) (InsertSpaceInvitationSubmissionRow, error) {
	row := q.db.QueryRow(ctx, insertSpaceInvitationSubmission,
		arg.SubmissionID,
		arg.InvitationID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.RecipientEmail,
		arg.PayloadDigest,
		arg.ProviderIdempotencyKey,
	)
	var i InsertSpaceInvitationSubmissionRow
	err := row.Scan(
		&i.SubmissionID,
		&i.RecipientEmail,
		&i.PayloadDigest,
		&i.ProviderIdempotencyKey,
		&i.State,
		&i.ProviderMessageID,
		&i.CreatedAt,
		&i.SubmitEligible,
	)
	return i, err
}

const listInvitationsForEmailOwner = `-- name: ListInvitationsForEmailOwner :many
SELECT
    i.invitation_id, i.space_id, sp.name AS space_name,
    u.display_name AS inviter_display_name,
    i.can_manage_members, i.can_enroll_machines,
    i.created_at, i.expires_at
FROM email_identities AS e
INNER JOIN space_invitations AS i ON i.recipient_email = e.canonical_email
INNER JOIN spaces AS sp ON sp.space_id = i.space_id
INNER JOIN carry_users AS u ON u.user_id = i.inviter_user_id
WHERE e.user_id = $1
    AND i.accepted_at IS NULL
    AND i.revoked_at IS NULL
    AND i.expires_at > transaction_timestamp()
ORDER BY i.expires_at, i.invitation_id
LIMIT 50
`

type ListInvitationsForEmailOwnerRow struct {
	InvitationID       string
	SpaceID            string
	SpaceName          string
	InviterDisplayName *string
	CanManageMembers   bool
	CanEnrollMachines  bool
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
}

func (q *Queries) ListInvitationsForEmailOwner(ctx context.Context, userID string) ([]ListInvitationsForEmailOwnerRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsForEmailOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsForEmailOwnerRow
	for rows.Next() {
		var i ListInvitationsForEmailOwnerRow
		if err := rows.Scan(
			&i.InvitationID,
			&i.SpaceID,
			&i.SpaceName,
			&i.InviterDisplayName,
			&i.CanManageMembers,
			&i.CanEnrollMachines,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedSpaceInvitations = `-- name: ListManagedSpaceInvitations :many
SELECT
    i.invitation_id, i.space_id, i.recipient_email,
    u.display_name AS inviter_display_name,
    i.can_manage_members, i.can_enroll_machines,
    i.created_at, i.expires_at,
    s.submission_id, s.recipient_email AS submission_recipient,
    s.payload_digest, s.provider_idempotency_key, s.state,
    s.provider_message_id, s.created_at AS submission_created_at
FROM space_invitations AS i
INNER JOIN carry_users AS u ON u.user_id = i.inviter_user_id
INNER JOIN LATERAL (
    SELECT submission_id, invitation_id, requested_by_user_id, idempotency_key, request_digest, recipient_email, payload_digest, provider_idempotency_key, state, provider_message_id, created_at, recorded_at FROM space_invitation_submissions
    WHERE invitation_id = i.invitation_id
    ORDER BY created_at DESC, submission_id DESC
    LIMIT 1
) AS s ON true
WHERE i.space_id = $1
    AND i.accepted_at IS NULL
    AND i.revoked_at IS NULL
    AND i.expires_at > transaction_timestamp()
ORDER BY i.created_at, i.invitation_id
LIMIT 50
`

type ListManagedSpaceInvitationsRow struct {
	InvitationID           string
	SpaceID                string
	RecipientEmail         string
	InviterDisplayName     *string
	CanManageMembers       bool
	CanEnrollMachines      bool
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	SubmissionID           string
	SubmissionRecipient    string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	SubmissionCreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListManagedSpaceInvitations(ctx context.Context, spaceID string) ([]ListManagedSpaceInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listManagedSpaceInvitations, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagedSpaceInvitationsRow
	for rows.Next() {
		var i ListManagedSpaceInvitationsRow
		if err := rows.Scan(
			&i.InvitationID,
			&i.SpaceID,
			&i.RecipientEmail,
			&i.InviterDisplayName,
			&i.CanManageMembers,
			&i.CanEnrollMachines,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.SubmissionID,
			&i.SubmissionRecipient,
			&i.PayloadDigest,
			&i.ProviderIdempotencyKey,
			&i.State,
			&i.ProviderMessageID,
			&i.SubmissionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadInvitationEmailOwner = `-- name: LoadInvitationEmailOwner :one
SELECT user_id
FROM email_identities
WHERE canonical_email = $1
`

func (q *Queries) LoadInvitationEmailOwner(ctx context.Context, recipientEmail string) (string, error) {
	row := q.db.QueryRow(ctx, loadInvitationEmailOwner, recipientEmail)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const loadInvitationInboxSession = `-- name: LoadInvitationInboxSession :one
SELECT bs.user_id, bs.identity_proved_at, bs.identity_proof_method,
    bs.expires_at, bs.revoked_at
FROM browser_sessions AS bs
WHERE bs.session_id = $1
FOR UPDATE
`

type LoadInvitationInboxSessionRow struct {
	UserID              string
	IdentityProvedAt    pgtype.Timestamptz
	IdentityProofMethod string
	ExpiresAt           pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
}

func (q *Queries) LoadInvitationInboxSession(ctx context.Context, sessionID string) (LoadInvitationInboxSessionRow, error) {
	row := q.db.QueryRow(ctx, loadInvitationInboxSession, sessionID)
	var i LoadInvitationInboxSessionRow
	err := row.Scan(
		&i.UserID,
		&i.IdentityProvedAt,
		&i.IdentityProofMethod,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const loadInvitationIssueReplay = `-- name: LoadInvitationIssueReplay :one
SELECT
    i.invitation_id, i.space_id, i.recipient_email, i.can_manage_members,
    i.can_enroll_machines, i.created_at, i.expires_at, i.issue_request_digest,
    s.submission_id, s.recipient_email AS submission_recipient,
    s.payload_digest, s.provider_idempotency_key, s.state,
    s.provider_message_id, s.created_at AS submission_created_at,
    (s.state = 'prepared'
        AND s.created_at + interval '24 hours' > transaction_timestamp()
        AND i.accepted_at IS NULL AND i.revoked_at IS NULL
        AND i.expires_at > transaction_timestamp()) AS submit_eligible
FROM space_invitations AS i
INNER JOIN space_invitation_submissions AS s ON s.invitation_id = i.invitation_id
WHERE i.space_id = $1
    AND i.inviter_user_id = $2
    AND i.issue_idempotency_key = $3
ORDER BY s.created_at, s.submission_id
LIMIT 1
`

type LoadInvitationIssueReplayParams struct {
	SpaceID        string
	UserID         string
	IdempotencyKey string
}

type LoadInvitationIssueReplayRow struct {
	InvitationID           string
	SpaceID                string
	RecipientEmail         string
	CanManageMembers       bool
	CanEnrollMachines      bool
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	IssueRequestDigest     []byte
	SubmissionID           string
	SubmissionRecipient    string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	SubmissionCreatedAt    pgtype.Timestamptz
	SubmitEligible         *bool
}

func (q *Queries) LoadInvitationIssueReplay(ctx context.Context, arg LoadInvitationIssueReplayParams) (LoadInvitationIssueReplayRow, error) {
	row := q.db.QueryRow(ctx, loadInvitationIssueReplay, arg.SpaceID, arg.UserID, arg.IdempotencyKey)
	var i LoadInvitationIssueReplayRow
	err := row.Scan(
		&i.InvitationID,
		&i.SpaceID,
		&i.RecipientEmail,
		&i.CanManageMembers,
		&i.CanEnrollMachines,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IssueRequestDigest,
		&i.SubmissionID,
		&i.SubmissionRecipient,
		&i.PayloadDigest,
		&i.ProviderIdempotencyKey,
		&i.State,
		&i.ProviderMessageID,
		&i.SubmissionCreatedAt,
		&i.SubmitEligible,
	)
	return i, err
}

const loadInvitationResendReplay = `-- name: LoadInvitationResendReplay :one
SELECT
    i.invitation_id, i.space_id, i.recipient_email, i.can_manage_members,
    i.can_enroll_machines, i.created_at, i.expires_at,
    s.submission_id, s.recipient_email AS submission_recipient,
    s.payload_digest, s.provider_idempotency_key, s.state,
    s.provider_message_id, s.created_at AS submission_created_at,
    s.request_digest,
    (s.state = 'prepared'
        AND s.created_at + interval '24 hours' > transaction_timestamp()
        AND i.accepted_at IS NULL AND i.revoked_at IS NULL
        AND i.expires_at > transaction_timestamp()) AS submit_eligible
FROM space_invitation_submissions AS s
INNER JOIN space_invitations AS i ON i.invitation_id = s.invitation_id
WHERE s.invitation_id = $1
    AND i.space_id = $2
    AND s.requested_by_user_id = $3
    AND s.idempotency_key = $4
`

type LoadInvitationResendReplayParams struct {
	InvitationID   string
	SpaceID        string
	UserID         string
	IdempotencyKey string
}

type LoadInvitationResendReplayRow struct {
	InvitationID           string
	SpaceID                string
	RecipientEmail         string
	CanManageMembers       bool
	CanEnrollMachines      bool
	CreatedAt              pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	SubmissionID           string
	SubmissionRecipient    string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	SubmissionCreatedAt    pgtype.Timestamptz
	RequestDigest          []byte
	SubmitEligible         *bool
}

func (q *Queries) LoadInvitationResendReplay(ctx context.Context, arg LoadInvitationResendReplayParams) (LoadInvitationResendReplayRow, error) {
	row := q.db.QueryRow(ctx, loadInvitationResendReplay,
		arg.InvitationID,
		arg.SpaceID,
		arg.UserID,
		arg.IdempotencyKey,
	)
	var i LoadInvitationResendReplayRow
	err := row.Scan(
		&i.InvitationID,
		&i.SpaceID,
		&i.RecipientEmail,
		&i.CanManageMembers,
		&i.CanEnrollMachines,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SubmissionID,
		&i.SubmissionRecipient,
		&i.PayloadDigest,
		&i.ProviderIdempotencyKey,
		&i.State,
		&i.ProviderMessageID,
		&i.SubmissionCreatedAt,
		&i.RequestDigest,
		&i.SubmitEligible,
	)
	return i, err
}

const loadInvitationSpaceName = `-- name: LoadInvitationSpaceName :one
SELECT name FROM spaces WHERE space_id = $1
`

func (q *Queries) LoadInvitationSpaceName(ctx context.Context, spaceID string) (string, error) {
	row := q.db.QueryRow(ctx, loadInvitationSpaceName, spaceID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const loadInvitationSubmission = `-- name: LoadInvitationSubmission :one
SELECT submission_id, invitation_id, recipient_email, payload_digest,
    provider_idempotency_key, state, provider_message_id, created_at,
    requested_by_user_id, idempotency_key, request_digest
FROM space_invitation_submissions
WHERE submission_id = $1
`

type LoadInvitationSubmissionRow struct {
	SubmissionID           string
	InvitationID           string
	RecipientEmail         string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	CreatedAt              pgtype.Timestamptz
	RequestedByUserID      string
	IdempotencyKey         string
	RequestDigest          []byte
}

func (q *Queries) LoadInvitationSubmission(ctx context.Context, submissionID string) (LoadInvitationSubmissionRow, error) {
	row := q.db.QueryRow(ctx, loadInvitationSubmission, submissionID)
	var i LoadInvitationSubmissionRow
	err := row.Scan(
		&i.SubmissionID,
		&i.InvitationID,
		&i.RecipientEmail,
		&i.PayloadDigest,
		&i.ProviderIdempotencyKey,
		&i.State,
		&i.ProviderMessageID,
		&i.CreatedAt,
		&i.RequestedByUserID,
		&i.IdempotencyKey,
		&i.RequestDigest,
	)
	return i, err
}

const loadLatestInvitationSubmissionTime = `-- name: LoadLatestInvitationSubmissionTime :one
SELECT created_at
FROM space_invitation_submissions
WHERE invitation_id = $1
ORDER BY created_at DESC, submission_id DESC
LIMIT 1
`

func (q *Queries) LoadLatestInvitationSubmissionTime(ctx context.Context, invitationID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, loadLatestInvitationSubmissionTime, invitationID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const loadMembershipForInvitation = `-- name: LoadMembershipForInvitation :one
SELECT can_manage_members, can_enroll_machines, revoked_at
FROM space_memberships
WHERE space_id = $1
    AND user_id = $2
FOR UPDATE
`

type LoadMembershipForInvitationParams struct {
	SpaceID string
	UserID  string
}

type LoadMembershipForInvitationRow struct {
	CanManageMembers  bool
	CanEnrollMachines bool
	RevokedAt         pgtype.Timestamptz
}

func (q *Queries) LoadMembershipForInvitation(ctx context.Context, arg LoadMembershipForInvitationParams) (LoadMembershipForInvitationRow, error) {
	row := q.db.QueryRow(ctx, loadMembershipForInvitation, arg.SpaceID, arg.UserID)
	var i LoadMembershipForInvitationRow
	err := row.Scan(&i.CanManageMembers, &i.CanEnrollMachines, &i.RevokedAt)
	return i, err
}

const loadSpaceInvitation = `-- name: LoadSpaceInvitation :one
SELECT invitation_id, space_id, recipient_email, inviter_user_id,
    can_manage_members, can_enroll_machines, created_at, expires_at,
    accepted_by_user_id, accepted_at, accept_result,
    accept_idempotency_key, accept_request_digest,
    revoked_by_user_id, revoked_at, revoke_idempotency_key, revoke_request_digest
FROM space_invitations
WHERE invitation_id = $1
`

type LoadSpaceInvitationRow struct {
	InvitationID         string
	SpaceID              string
	RecipientEmail       string
	InviterUserID        string
	CanManageMembers     bool
	CanEnrollMachines    bool
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	AcceptedByUserID     pgtype.UUID
	AcceptedAt           pgtype.Timestamptz
	AcceptResult         *string
	AcceptIdempotencyKey *string
	AcceptRequestDigest  []byte
	RevokedByUserID      pgtype.UUID
	RevokedAt            pgtype.Timestamptz
	RevokeIdempotencyKey *string
	RevokeRequestDigest  []byte
}

func (q *Queries) LoadSpaceInvitation(ctx context.Context, invitationID string) (LoadSpaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, loadSpaceInvitation, invitationID)
	var i LoadSpaceInvitationRow
	err := row.Scan(
		&i.InvitationID,
		&i.SpaceID,
		&i.RecipientEmail,
		&i.InviterUserID,
		&i.CanManageMembers,
		&i.CanEnrollMachines,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedByUserID,
		&i.AcceptedAt,
		&i.AcceptResult,
		&i.AcceptIdempotencyKey,
		&i.AcceptRequestDigest,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevokeIdempotencyKey,
		&i.RevokeRequestDigest,
	)
	return i, err
}

const loadSpaceInvitationForUpdate = `-- name: LoadSpaceInvitationForUpdate :one
SELECT invitation_id, space_id, recipient_email, inviter_user_id,
    can_manage_members, can_enroll_machines, created_at, expires_at,
    accepted_by_user_id, accepted_at, accept_result,
    accept_idempotency_key, accept_request_digest,
    revoked_by_user_id, revoked_at, revoke_idempotency_key, revoke_request_digest
FROM space_invitations
WHERE invitation_id = $1
FOR UPDATE
`

type LoadSpaceInvitationForUpdateRow struct {
	InvitationID         string
	SpaceID              string
	RecipientEmail       string
	InviterUserID        string
	CanManageMembers     bool
	CanEnrollMachines    bool
	CreatedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	AcceptedByUserID     pgtype.UUID
	AcceptedAt           pgtype.Timestamptz
	AcceptResult         *string
	AcceptIdempotencyKey *string
	AcceptRequestDigest  []byte
	RevokedByUserID      pgtype.UUID
	RevokedAt            pgtype.Timestamptz
	RevokeIdempotencyKey *string
	RevokeRequestDigest  []byte
}

func (q *Queries) LoadSpaceInvitationForUpdate(ctx context.Context, invitationID string) (LoadSpaceInvitationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, loadSpaceInvitationForUpdate, invitationID)
	var i LoadSpaceInvitationForUpdateRow
	err := row.Scan(
		&i.InvitationID,
		&i.SpaceID,
		&i.RecipientEmail,
		&i.InviterUserID,
		&i.CanManageMembers,
		&i.CanEnrollMachines,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedByUserID,
		&i.AcceptedAt,
		&i.AcceptResult,
		&i.AcceptIdempotencyKey,
		&i.AcceptRequestDigest,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevokeIdempotencyKey,
		&i.RevokeRequestDigest,
	)
	return i, err
}

const lockInvitationActorMembership = `-- name: LockInvitationActorMembership :one
SELECT can_manage_members, can_enroll_machines
FROM space_memberships
WHERE space_id = $1
    AND user_id = $2
    AND revoked_at IS NULL
FOR UPDATE
`

type LockInvitationActorMembershipParams struct {
	SpaceID string
	UserID  string
}

type LockInvitationActorMembershipRow struct {
	CanManageMembers  bool
	CanEnrollMachines bool
}

func (q *Queries) LockInvitationActorMembership(ctx context.Context, arg LockInvitationActorMembershipParams) (LockInvitationActorMembershipRow, error) {
	row := q.db.QueryRow(ctx, lockInvitationActorMembership, arg.SpaceID, arg.UserID)
	var i LockInvitationActorMembershipRow
	err := row.Scan(&i.CanManageMembers, &i.CanEnrollMachines)
	return i, err
}

const lockInvitationUser = `-- name: LockInvitationUser :one
SELECT display_name
FROM carry_users
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockInvitationUser(ctx context.Context, userID string) (*string, error) {
	row := q.db.QueryRow(ctx, lockInvitationUser, userID)
	var display_name *string
	err := row.Scan(&display_name)
	return display_name, err
}

const lockSpaceInvitationRecipientKey = `-- name: LockSpaceInvitationRecipientKey :exec
SELECT pg_advisory_xact_lock(hashtextextended(
    $1::text || '|' || $2::text,
    934771
))
`

type LockSpaceInvitationRecipientKeyParams struct {
	SpaceID        string
	RecipientEmail string
}

func (q *Queries) LockSpaceInvitationRecipientKey(ctx context.Context, arg LockSpaceInvitationRecipientKeyParams) error {
	_, err := q.db.Exec(ctx, lockSpaceInvitationRecipientKey, arg.SpaceID, arg.RecipientEmail)
	return err
}

const recordSpaceInvitationSubmission = `-- name: RecordSpaceInvitationSubmission :one
UPDATE space_invitation_submissions
SET
    state = $1,
    provider_message_id = $2,
    recorded_at = COALESCE(recorded_at, transaction_timestamp())
WHERE submission_id = $3
    AND payload_digest = $4
    AND (
        state = 'prepared'
        OR (
            state = $1
            AND provider_message_id IS NOT DISTINCT FROM $2
        )
    )
RETURNING submission_id, recipient_email, payload_digest,
    provider_idempotency_key, state, provider_message_id, created_at
`

type RecordSpaceInvitationSubmissionParams struct {
	State             string
	ProviderMessageID *string
	SubmissionID      string
	PayloadDigest     []byte
}

type RecordSpaceInvitationSubmissionRow struct {
	SubmissionID           string
	RecipientEmail         string
	PayloadDigest          []byte
	ProviderIdempotencyKey string
	State                  string
	ProviderMessageID      *string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) RecordSpaceInvitationSubmission(ctx context.Context, arg RecordSpaceInvitationSubmissionParams) (RecordSpaceInvitationSubmissionRow, error) {
	row := q.db.QueryRow(ctx, recordSpaceInvitationSubmission,
		arg.State,
		arg.ProviderMessageID,
		arg.SubmissionID,
		arg.PayloadDigest,
	)
	var i RecordSpaceInvitationSubmissionRow
	err := row.Scan(
		&i.SubmissionID,
		&i.RecipientEmail,
		&i.PayloadDigest,
		&i.ProviderIdempotencyKey,
		&i.State,
		&i.ProviderMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSpaceInvitation = `-- name: RevokeSpaceInvitation :execrows
UPDATE space_invitations
SET
    revoked_by_user_id = $1,
    revoked_at = transaction_timestamp(),
    revoke_idempotency_key = $2,
    revoke_request_digest = $3
WHERE invitation_id = $4
    AND accepted_at IS NULL
    AND revoked_at IS NULL
    AND expires_at > transaction_timestamp()
`

type RevokeSpaceInvitationParams struct {
	UserID         pgtype.UUID
	IdempotencyKey *string
	RequestDigest  []byte
	InvitationID   string
}

func (q *Queries) RevokeSpaceInvitation(ctx context.Context, arg RevokeSpaceInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSpaceInvitation,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.InvitationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInvitationAcceptedUserName = `-- name: SetInvitationAcceptedUserName :exec
UPDATE carry_users
SET display_name = $1
WHERE user_id = $2
    AND display_name IS NULL
`

type SetInvitationAcceptedUserNameParams struct {
	DisplayName *string
	UserID      string
}

func (q *Queries) SetInvitationAcceptedUserName(ctx context.Context, arg SetInvitationAcceptedUserNameParams) error {
	_, err := q.db.Exec(ctx, setInvitationAcceptedUserName, arg.DisplayName, arg.UserID)
	return err
}
