// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_creation.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpace = `-- name: CreateSpace :exec
INSERT INTO spaces (
    space_id,
    name,
    slug,
    created_by_user_id,
    create_idempotency_key,
    create_request_digest
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateSpaceParams struct {
	SpaceID        string
	Name           string
	Slug           string
	UserID         pgtype.UUID
	IdempotencyKey *string
	RequestDigest  []byte
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) error {
	_, err := q.db.Exec(ctx, createSpace,
		arg.SpaceID,
		arg.Name,
		arg.Slug,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
	)
	return err
}

const createSpaceMembership = `-- name: CreateSpaceMembership :exec
INSERT INTO space_memberships (
    space_id,
    user_id,
    can_enroll_machines,
    can_manage_members
) VALUES (
    $1,
    $2,
    true,
    true
)
`

type CreateSpaceMembershipParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) CreateSpaceMembership(ctx context.Context, arg CreateSpaceMembershipParams) error {
	_, err := q.db.Exec(ctx, createSpaceMembership, arg.SpaceID, arg.UserID)
	return err
}

const loadCreatedSpaceByRequest = `-- name: LoadCreatedSpaceByRequest :one
SELECT
    s.space_id,
    s.name,
    s.slug,
    s.created_by_user_id,
    s.create_request_digest,
    m.can_manage_members,
    m.can_enroll_machines
FROM spaces AS s
INNER JOIN space_memberships AS m
    ON m.space_id = s.space_id
    AND m.user_id = s.created_by_user_id
WHERE s.created_by_user_id = $1
    AND s.create_idempotency_key = $2
`

type LoadCreatedSpaceByRequestParams struct {
	UserID         pgtype.UUID
	IdempotencyKey *string
}

type LoadCreatedSpaceByRequestRow struct {
	SpaceID             string
	Name                string
	Slug                string
	CreatedByUserID     pgtype.UUID
	CreateRequestDigest []byte
	CanManageMembers    bool
	CanEnrollMachines   bool
}

func (q *Queries) LoadCreatedSpaceByRequest(ctx context.Context, arg LoadCreatedSpaceByRequestParams) (LoadCreatedSpaceByRequestRow, error) {
	row := q.db.QueryRow(ctx, loadCreatedSpaceByRequest, arg.UserID, arg.IdempotencyKey)
	var i LoadCreatedSpaceByRequestRow
	err := row.Scan(
		&i.SpaceID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreateRequestDigest,
		&i.CanManageMembers,
		&i.CanEnrollMachines,
	)
	return i, err
}

const lockSpaceCreator = `-- name: LockSpaceCreator :one
SELECT user_id
FROM carry_users
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockSpaceCreator(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, lockSpaceCreator, userID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
