// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: space_creation.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFirstSpace = `-- name: CreateFirstSpace :exec
INSERT INTO spaces (
    space_id,
    name,
    created_by_user_id,
    create_idempotency_key,
    create_request_digest
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateFirstSpaceParams struct {
	SpaceID        string
	Name           string
	UserID         pgtype.UUID
	IdempotencyKey *string
	RequestDigest  []byte
}

func (q *Queries) CreateFirstSpace(ctx context.Context, arg CreateFirstSpaceParams) error {
	_, err := q.db.Exec(ctx, createFirstSpace,
		arg.SpaceID,
		arg.Name,
		arg.UserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
	)
	return err
}

const createFirstSpaceMembership = `-- name: CreateFirstSpaceMembership :exec
INSERT INTO space_memberships (
    space_id,
    user_id,
    can_enroll_machines,
    can_manage_members
) VALUES (
    $1,
    $2,
    true,
    true
)
`

type CreateFirstSpaceMembershipParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) CreateFirstSpaceMembership(ctx context.Context, arg CreateFirstSpaceMembershipParams) error {
	_, err := q.db.Exec(ctx, createFirstSpaceMembership, arg.SpaceID, arg.UserID)
	return err
}

const hasActiveMembership = `-- name: HasActiveMembership :one
SELECT exists(
    SELECT 1
    FROM space_memberships
    WHERE user_id = $1
        AND revoked_at IS NULL
)
`

func (q *Queries) HasActiveMembership(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveMembership, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loadCreatedSpaceByRequest = `-- name: LoadCreatedSpaceByRequest :one
SELECT
    s.space_id,
    s.name,
    s.created_by_user_id,
    s.create_request_digest,
    m.can_manage_members,
    m.can_enroll_machines
FROM spaces AS s
INNER JOIN space_memberships AS m
    ON m.space_id = s.space_id
    AND m.user_id = s.created_by_user_id
WHERE s.created_by_user_id = $1
    AND s.create_idempotency_key = $2
`

type LoadCreatedSpaceByRequestParams struct {
	UserID         pgtype.UUID
	IdempotencyKey *string
}

type LoadCreatedSpaceByRequestRow struct {
	SpaceID             string
	Name                string
	CreatedByUserID     pgtype.UUID
	CreateRequestDigest []byte
	CanManageMembers    bool
	CanEnrollMachines   bool
}

func (q *Queries) LoadCreatedSpaceByRequest(ctx context.Context, arg LoadCreatedSpaceByRequestParams) (LoadCreatedSpaceByRequestRow, error) {
	row := q.db.QueryRow(ctx, loadCreatedSpaceByRequest, arg.UserID, arg.IdempotencyKey)
	var i LoadCreatedSpaceByRequestRow
	err := row.Scan(
		&i.SpaceID,
		&i.Name,
		&i.CreatedByUserID,
		&i.CreateRequestDigest,
		&i.CanManageMembers,
		&i.CanEnrollMachines,
	)
	return i, err
}

const lockSpaceCreator = `-- name: LockSpaceCreator :one
SELECT display_name
FROM carry_users
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockSpaceCreator(ctx context.Context, userID string) (*string, error) {
	row := q.db.QueryRow(ctx, lockSpaceCreator, userID)
	var display_name *string
	err := row.Scan(&display_name)
	return display_name, err
}

const setInitialDisplayName = `-- name: SetInitialDisplayName :exec
UPDATE carry_users
SET display_name = $1
WHERE user_id = $2
    AND display_name IS NULL
`

type SetInitialDisplayNameParams struct {
	DisplayName *string
	UserID      string
}

func (q *Queries) SetInitialDisplayName(ctx context.Context, arg SetInitialDisplayNameParams) error {
	_, err := q.db.Exec(ctx, setInitialDisplayName, arg.DisplayName, arg.UserID)
	return err
}
