// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceWorkInputHead = `-- name: AdvanceWorkInputHead :one
UPDATE works
SET input_head_seq = input_head_seq + 1
WHERE work_id = $1 AND lifecycle = 'open'
RETURNING input_head_seq
`

func (q *Queries) AdvanceWorkInputHead(ctx context.Context, workID string) (int64, error) {
	row := q.db.QueryRow(ctx, advanceWorkInputHead, workID)
	var input_head_seq int64
	err := row.Scan(&input_head_seq)
	return input_head_seq, err
}

const createWork = `-- name: CreateWork :one
WITH created AS (
    INSERT INTO works (
        work_id,
        space_id,
        goal,
        owner_user_id,
        creator_user_id,
        create_idempotency_key,
        create_request_digest
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
    ON CONFLICT (space_id, creator_user_id, create_idempotency_key) DO NOTHING
    RETURNING work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id, input_head_seq, create_idempotency_key, create_request_digest, created_at, applied_input_seq, understanding_version, understanding, next_step
)
SELECT
    created.work_id,
    created.space_id,
    created.goal,
    created.lifecycle,
    created.owner_user_id,
    owner.display_name AS owner_display_name,
    created.creator_user_id,
    creator.display_name AS creator_display_name,
    created.input_head_seq,
    created.applied_input_seq,
    created.understanding,
    created.next_step,
    created.created_at
FROM created
JOIN carry_users AS owner ON owner.user_id = created.owner_user_id
JOIN carry_users AS creator ON creator.user_id = created.creator_user_id
`

type CreateWorkParams struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	OwnerUserID          string
	CreatorUserID        string
	CreateIdempotencyKey string
	CreateRequestDigest  []byte
}

type CreateWorkRow struct {
	WorkID             string
	SpaceID            string
	Goal               string
	Lifecycle          string
	OwnerUserID        string
	OwnerDisplayName   string
	CreatorUserID      string
	CreatorDisplayName string
	InputHeadSeq       int64
	AppliedInputSeq    int64
	Understanding      *string
	NextStep           *string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateWork(ctx context.Context, arg CreateWorkParams) (CreateWorkRow, error) {
	row := q.db.QueryRow(ctx, createWork,
		arg.WorkID,
		arg.SpaceID,
		arg.Goal,
		arg.OwnerUserID,
		arg.CreatorUserID,
		arg.CreateIdempotencyKey,
		arg.CreateRequestDigest,
	)
	var i CreateWorkRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.OwnerDisplayName,
		&i.CreatorUserID,
		&i.CreatorDisplayName,
		&i.InputHeadSeq,
		&i.AppliedInputSeq,
		&i.Understanding,
		&i.NextStep,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkMessage = `-- name: CreateWorkMessage :one
WITH created AS (
    INSERT INTO work_messages (
        message_id,
        work_id,
        author_user_id,
        text,
        input_seq,
        idempotency_key,
        request_digest
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
    RETURNING message_id, work_id, author_user_id, text, input_seq, idempotency_key, request_digest, created_at
)
SELECT
    created.message_id,
    created.work_id,
    created.author_user_id,
    author.display_name AS author_display_name,
    created.text,
    created.input_seq,
    created.created_at
FROM created
JOIN carry_users AS author ON author.user_id = created.author_user_id
`

type CreateWorkMessageParams struct {
	MessageID      string
	WorkID         string
	AuthorUserID   string
	Text           string
	InputSeq       int64
	IdempotencyKey string
	RequestDigest  []byte
}

type CreateWorkMessageRow struct {
	MessageID         string
	WorkID            string
	AuthorUserID      string
	AuthorDisplayName string
	Text              string
	InputSeq          int64
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateWorkMessage(ctx context.Context, arg CreateWorkMessageParams) (CreateWorkMessageRow, error) {
	row := q.db.QueryRow(ctx, createWorkMessage,
		arg.MessageID,
		arg.WorkID,
		arg.AuthorUserID,
		arg.Text,
		arg.InputSeq,
		arg.IdempotencyKey,
		arg.RequestDigest,
	)
	var i CreateWorkMessageRow
	err := row.Scan(
		&i.MessageID,
		&i.WorkID,
		&i.AuthorUserID,
		&i.AuthorDisplayName,
		&i.Text,
		&i.InputSeq,
		&i.CreatedAt,
	)
	return i, err
}

const findWorkByCreateIdempotency = `-- name: FindWorkByCreateIdempotency :one
SELECT
    work.work_id,
    work.space_id,
    work.goal,
    work.lifecycle,
    work.owner_user_id,
    owner.display_name AS owner_display_name,
    work.creator_user_id,
    creator.display_name AS creator_display_name,
    work.input_head_seq,
    work.applied_input_seq,
    work.understanding,
    work.next_step,
    work.created_at,
    work.create_request_digest,
    EXISTS (
        SELECT 1 FROM runs
        WHERE runs.work_id = work.work_id
          AND runs.state IN ('failed', 'unknown')
          AND runs.retry_requested_at IS NULL
    ) AS needs_retry
FROM works AS work
JOIN carry_users AS owner ON owner.user_id = work.owner_user_id
JOIN carry_users AS creator ON creator.user_id = work.creator_user_id
WHERE
    work.space_id = $1
    AND work.creator_user_id = $2
    AND work.create_idempotency_key = $3
`

type FindWorkByCreateIdempotencyParams struct {
	SpaceID              string
	CreatorUserID        string
	CreateIdempotencyKey string
}

type FindWorkByCreateIdempotencyRow struct {
	WorkID              string
	SpaceID             string
	Goal                string
	Lifecycle           string
	OwnerUserID         string
	OwnerDisplayName    string
	CreatorUserID       string
	CreatorDisplayName  string
	InputHeadSeq        int64
	AppliedInputSeq     int64
	Understanding       *string
	NextStep            *string
	CreatedAt           pgtype.Timestamptz
	CreateRequestDigest []byte
	NeedsRetry          bool
}

func (q *Queries) FindWorkByCreateIdempotency(ctx context.Context, arg FindWorkByCreateIdempotencyParams) (FindWorkByCreateIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findWorkByCreateIdempotency, arg.SpaceID, arg.CreatorUserID, arg.CreateIdempotencyKey)
	var i FindWorkByCreateIdempotencyRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.OwnerDisplayName,
		&i.CreatorUserID,
		&i.CreatorDisplayName,
		&i.InputHeadSeq,
		&i.AppliedInputSeq,
		&i.Understanding,
		&i.NextStep,
		&i.CreatedAt,
		&i.CreateRequestDigest,
		&i.NeedsRetry,
	)
	return i, err
}

const findWorkMessageByIdempotency = `-- name: FindWorkMessageByIdempotency :one
SELECT
    message.message_id,
    message.work_id,
    message.author_user_id,
    author.display_name AS author_display_name,
    message.text,
    message.input_seq,
    message.created_at,
    message.request_digest
FROM work_messages AS message
JOIN carry_users AS author ON author.user_id = message.author_user_id
WHERE
    message.work_id = $1
    AND message.author_user_id = $2
    AND message.idempotency_key = $3
`

type FindWorkMessageByIdempotencyParams struct {
	WorkID         string
	AuthorUserID   string
	IdempotencyKey string
}

type FindWorkMessageByIdempotencyRow struct {
	MessageID         string
	WorkID            string
	AuthorUserID      string
	AuthorDisplayName string
	Text              string
	InputSeq          int64
	CreatedAt         pgtype.Timestamptz
	RequestDigest     []byte
}

func (q *Queries) FindWorkMessageByIdempotency(ctx context.Context, arg FindWorkMessageByIdempotencyParams) (FindWorkMessageByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findWorkMessageByIdempotency, arg.WorkID, arg.AuthorUserID, arg.IdempotencyKey)
	var i FindWorkMessageByIdempotencyRow
	err := row.Scan(
		&i.MessageID,
		&i.WorkID,
		&i.AuthorUserID,
		&i.AuthorDisplayName,
		&i.Text,
		&i.InputSeq,
		&i.CreatedAt,
		&i.RequestDigest,
	)
	return i, err
}

const listNewestWorkMessages = `-- name: ListNewestWorkMessages :many
WITH candidates AS (
    SELECT message_id, work_id, author_user_id, text, input_seq, created_at
    FROM work_messages
    WHERE work_id = $1
    ORDER BY input_seq DESC
    LIMIT 50
), bounded AS (
    SELECT
        candidates.message_id, candidates.work_id, candidates.author_user_id, candidates.text, candidates.input_seq, candidates.created_at,
        sum(octet_length(text)) OVER (
            ORDER BY input_seq DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS text_bytes
    FROM candidates
)
SELECT
    bounded.message_id,
    bounded.work_id,
    bounded.author_user_id,
    author.display_name AS author_display_name,
    bounded.text,
    bounded.input_seq,
    bounded.created_at
FROM bounded
JOIN carry_users AS author ON author.user_id = bounded.author_user_id
WHERE bounded.text_bytes <= 262144
ORDER BY bounded.input_seq
`

type ListNewestWorkMessagesRow struct {
	MessageID         string
	WorkID            string
	AuthorUserID      string
	AuthorDisplayName string
	Text              string
	InputSeq          int64
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListNewestWorkMessages(ctx context.Context, workID string) ([]ListNewestWorkMessagesRow, error) {
	rows, err := q.db.Query(ctx, listNewestWorkMessages, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewestWorkMessagesRow
	for rows.Next() {
		var i ListNewestWorkMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.WorkID,
			&i.AuthorUserID,
			&i.AuthorDisplayName,
			&i.Text,
			&i.InputSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestWorks = `-- name: ListNewestWorks :many
SELECT
    work.work_id,
    work.space_id,
    work.goal,
    work.lifecycle,
    work.owner_user_id,
    owner.display_name AS owner_display_name,
    work.creator_user_id,
    creator.display_name AS creator_display_name,
    work.input_head_seq,
    work.applied_input_seq,
    work.created_at,
    EXISTS (
        SELECT 1 FROM runs
        WHERE runs.work_id = work.work_id
          AND runs.state IN ('failed', 'unknown')
          AND runs.retry_requested_at IS NULL
    ) AS needs_retry
FROM works AS work
JOIN carry_users AS owner ON owner.user_id = work.owner_user_id
JOIN carry_users AS creator ON creator.user_id = work.creator_user_id
WHERE work.space_id = $1
ORDER BY work.created_at DESC, work.work_id DESC
LIMIT 51
`

type ListNewestWorksRow struct {
	WorkID             string
	SpaceID            string
	Goal               string
	Lifecycle          string
	OwnerUserID        string
	OwnerDisplayName   string
	CreatorUserID      string
	CreatorDisplayName string
	InputHeadSeq       int64
	AppliedInputSeq    int64
	CreatedAt          pgtype.Timestamptz
	NeedsRetry         bool
}

func (q *Queries) ListNewestWorks(ctx context.Context, spaceID string) ([]ListNewestWorksRow, error) {
	rows, err := q.db.Query(ctx, listNewestWorks, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewestWorksRow
	for rows.Next() {
		var i ListNewestWorksRow
		if err := rows.Scan(
			&i.WorkID,
			&i.SpaceID,
			&i.Goal,
			&i.Lifecycle,
			&i.OwnerUserID,
			&i.OwnerDisplayName,
			&i.CreatorUserID,
			&i.CreatorDisplayName,
			&i.InputHeadSeq,
			&i.AppliedInputSeq,
			&i.CreatedAt,
			&i.NeedsRetry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkMessagesBefore = `-- name: ListWorkMessagesBefore :many
WITH candidates AS (
    SELECT message_id, work_id, author_user_id, text, input_seq, created_at
    FROM work_messages
    WHERE work_id = $1 AND input_seq < $2
    ORDER BY input_seq DESC
    LIMIT 50
), bounded AS (
    SELECT
        candidates.message_id, candidates.work_id, candidates.author_user_id, candidates.text, candidates.input_seq, candidates.created_at,
        sum(octet_length(text)) OVER (
            ORDER BY input_seq DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS text_bytes
    FROM candidates
)
SELECT
    bounded.message_id,
    bounded.work_id,
    bounded.author_user_id,
    author.display_name AS author_display_name,
    bounded.text,
    bounded.input_seq,
    bounded.created_at
FROM bounded
JOIN carry_users AS author ON author.user_id = bounded.author_user_id
WHERE bounded.text_bytes <= 262144
ORDER BY bounded.input_seq
`

type ListWorkMessagesBeforeParams struct {
	WorkID         string
	CursorSequence int64
}

type ListWorkMessagesBeforeRow struct {
	MessageID         string
	WorkID            string
	AuthorUserID      string
	AuthorDisplayName string
	Text              string
	InputSeq          int64
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListWorkMessagesBefore(ctx context.Context, arg ListWorkMessagesBeforeParams) ([]ListWorkMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listWorkMessagesBefore, arg.WorkID, arg.CursorSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkMessagesBeforeRow
	for rows.Next() {
		var i ListWorkMessagesBeforeRow
		if err := rows.Scan(
			&i.MessageID,
			&i.WorkID,
			&i.AuthorUserID,
			&i.AuthorDisplayName,
			&i.Text,
			&i.InputSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorksBefore = `-- name: ListWorksBefore :many
SELECT
    work.work_id,
    work.space_id,
    work.goal,
    work.lifecycle,
    work.owner_user_id,
    owner.display_name AS owner_display_name,
    work.creator_user_id,
    creator.display_name AS creator_display_name,
    work.input_head_seq,
    work.applied_input_seq,
    work.created_at,
    EXISTS (
        SELECT 1 FROM runs
        WHERE runs.work_id = work.work_id
          AND runs.state IN ('failed', 'unknown')
          AND runs.retry_requested_at IS NULL
    ) AS needs_retry
FROM works AS work
JOIN carry_users AS owner ON owner.user_id = work.owner_user_id
JOIN carry_users AS creator ON creator.user_id = work.creator_user_id
WHERE
    work.space_id = $1
    AND (work.created_at, work.work_id) < (
        $2::timestamptz,
        $3::uuid
    )
ORDER BY work.created_at DESC, work.work_id DESC
LIMIT 51
`

type ListWorksBeforeParams struct {
	SpaceID         string
	CursorCreatedAt pgtype.Timestamptz
	CursorWorkID    string
}

type ListWorksBeforeRow struct {
	WorkID             string
	SpaceID            string
	Goal               string
	Lifecycle          string
	OwnerUserID        string
	OwnerDisplayName   string
	CreatorUserID      string
	CreatorDisplayName string
	InputHeadSeq       int64
	AppliedInputSeq    int64
	CreatedAt          pgtype.Timestamptz
	NeedsRetry         bool
}

func (q *Queries) ListWorksBefore(ctx context.Context, arg ListWorksBeforeParams) ([]ListWorksBeforeRow, error) {
	rows, err := q.db.Query(ctx, listWorksBefore, arg.SpaceID, arg.CursorCreatedAt, arg.CursorWorkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorksBeforeRow
	for rows.Next() {
		var i ListWorksBeforeRow
		if err := rows.Scan(
			&i.WorkID,
			&i.SpaceID,
			&i.Goal,
			&i.Lifecycle,
			&i.OwnerUserID,
			&i.OwnerDisplayName,
			&i.CreatorUserID,
			&i.CreatorDisplayName,
			&i.InputHeadSeq,
			&i.AppliedInputSeq,
			&i.CreatedAt,
			&i.NeedsRetry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadWork = `-- name: LoadWork :one
SELECT
    work.work_id,
    work.space_id,
    work.goal,
    work.lifecycle,
    work.owner_user_id,
    owner.display_name AS owner_display_name,
    work.creator_user_id,
    creator.display_name AS creator_display_name,
    work.input_head_seq,
    work.applied_input_seq,
    work.understanding,
    work.next_step,
    work.created_at,
    EXISTS (
        SELECT 1 FROM runs
        WHERE runs.work_id = work.work_id
          AND runs.state IN ('failed', 'unknown')
          AND runs.retry_requested_at IS NULL
    ) AS needs_retry
FROM works AS work
JOIN carry_users AS owner ON owner.user_id = work.owner_user_id
JOIN carry_users AS creator ON creator.user_id = work.creator_user_id
WHERE work.space_id = $1 AND work.work_id = $2
FOR SHARE OF work
`

type LoadWorkParams struct {
	SpaceID string
	WorkID  string
}

type LoadWorkRow struct {
	WorkID             string
	SpaceID            string
	Goal               string
	Lifecycle          string
	OwnerUserID        string
	OwnerDisplayName   string
	CreatorUserID      string
	CreatorDisplayName string
	InputHeadSeq       int64
	AppliedInputSeq    int64
	Understanding      *string
	NextStep           *string
	CreatedAt          pgtype.Timestamptz
	NeedsRetry         bool
}

func (q *Queries) LoadWork(ctx context.Context, arg LoadWorkParams) (LoadWorkRow, error) {
	row := q.db.QueryRow(ctx, loadWork, arg.SpaceID, arg.WorkID)
	var i LoadWorkRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.OwnerDisplayName,
		&i.CreatorUserID,
		&i.CreatorDisplayName,
		&i.InputHeadSeq,
		&i.AppliedInputSeq,
		&i.Understanding,
		&i.NextStep,
		&i.CreatedAt,
		&i.NeedsRetry,
	)
	return i, err
}

const lockActiveWorkMembership = `-- name: LockActiveWorkMembership :one
SELECT version
FROM space_memberships
WHERE
    space_id = $1
    AND user_id = $2
    AND revoked_at IS NULL
FOR SHARE
`

type LockActiveWorkMembershipParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) LockActiveWorkMembership(ctx context.Context, arg LockActiveWorkMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockActiveWorkMembership, arg.SpaceID, arg.UserID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockWork = `-- name: LockWork :one
SELECT work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id,
    input_head_seq, applied_input_seq, understanding_version, understanding, next_step, created_at
FROM works
WHERE space_id = $1 AND work_id = $2
FOR UPDATE
`

type LockWorkParams struct {
	SpaceID string
	WorkID  string
}

type LockWorkRow struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Lifecycle            string
	OwnerUserID          string
	CreatorUserID        string
	InputHeadSeq         int64
	AppliedInputSeq      int64
	UnderstandingVersion int64
	Understanding        *string
	NextStep             *string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) LockWork(ctx context.Context, arg LockWorkParams) (LockWorkRow, error) {
	row := q.db.QueryRow(ctx, lockWork, arg.SpaceID, arg.WorkID)
	var i LockWorkRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.CreatorUserID,
		&i.InputHeadSeq,
		&i.AppliedInputSeq,
		&i.UnderstandingVersion,
		&i.Understanding,
		&i.NextStep,
		&i.CreatedAt,
	)
	return i, err
}

const workHasMessagesBefore = `-- name: WorkHasMessagesBefore :one
SELECT EXISTS (
    SELECT 1 FROM work_messages
    WHERE work_id = $1 AND input_seq < $2
)
`

type WorkHasMessagesBeforeParams struct {
	WorkID   string
	InputSeq int64
}

func (q *Queries) WorkHasMessagesBefore(ctx context.Context, arg WorkHasMessagesBeforeParams) (bool, error) {
	row := q.db.QueryRow(ctx, workHasMessagesBefore, arg.WorkID, arg.InputSeq)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workListCursor = `-- name: WorkListCursor :one
SELECT created_at, work_id
FROM works
WHERE space_id = $1 AND work_id = $2
`

type WorkListCursorParams struct {
	SpaceID string
	WorkID  string
}

type WorkListCursorRow struct {
	CreatedAt pgtype.Timestamptz
	WorkID    string
}

func (q *Queries) WorkListCursor(ctx context.Context, arg WorkListCursorParams) (WorkListCursorRow, error) {
	row := q.db.QueryRow(ctx, workListCursor, arg.SpaceID, arg.WorkID)
	var i WorkListCursorRow
	err := row.Scan(&i.CreatedAt, &i.WorkID)
	return i, err
}

const workMessageCursorSequence = `-- name: WorkMessageCursorSequence :one
SELECT input_seq
FROM work_messages
WHERE work_id = $1 AND message_id = $2
`

type WorkMessageCursorSequenceParams struct {
	WorkID    string
	MessageID string
}

func (q *Queries) WorkMessageCursorSequence(ctx context.Context, arg WorkMessageCursorSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, workMessageCursorSequence, arg.WorkID, arg.MessageID)
	var input_seq int64
	err := row.Scan(&input_seq)
	return input_seq, err
}
