// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceWorkInputHead = `-- name: AdvanceWorkInputHead :one
UPDATE works
SET input_head_seq = input_head_seq + 1
WHERE work_id = $1 AND lifecycle = 'open'
RETURNING input_head_seq
`

func (q *Queries) AdvanceWorkInputHead(ctx context.Context, workID string) (int64, error) {
	row := q.db.QueryRow(ctx, advanceWorkInputHead, workID)
	var input_head_seq int64
	err := row.Scan(&input_head_seq)
	return input_head_seq, err
}

const createWork = `-- name: CreateWork :one
INSERT INTO works (
    work_id,
    space_id,
    goal,
    owner_user_id,
    creator_user_id,
    create_idempotency_key,
    create_request_digest
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (space_id, creator_user_id, create_idempotency_key) DO NOTHING
RETURNING work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id, created_at
`

type CreateWorkParams struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	OwnerUserID          string
	CreatorUserID        string
	CreateIdempotencyKey string
	CreateRequestDigest  []byte
}

type CreateWorkRow struct {
	WorkID        string
	SpaceID       string
	Goal          string
	Lifecycle     string
	OwnerUserID   string
	CreatorUserID string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateWork(ctx context.Context, arg CreateWorkParams) (CreateWorkRow, error) {
	row := q.db.QueryRow(ctx, createWork,
		arg.WorkID,
		arg.SpaceID,
		arg.Goal,
		arg.OwnerUserID,
		arg.CreatorUserID,
		arg.CreateIdempotencyKey,
		arg.CreateRequestDigest,
	)
	var i CreateWorkRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.CreatorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkMessage = `-- name: CreateWorkMessage :one
INSERT INTO work_messages (
    message_id,
    work_id,
    author_user_id,
    text,
    input_seq,
    idempotency_key,
    request_digest
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING message_id, work_id, author_user_id, text, input_seq, created_at
`

type CreateWorkMessageParams struct {
	MessageID      string
	WorkID         string
	AuthorUserID   string
	Text           string
	InputSeq       int64
	IdempotencyKey string
	RequestDigest  []byte
}

type CreateWorkMessageRow struct {
	MessageID    string
	WorkID       string
	AuthorUserID string
	Text         string
	InputSeq     int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateWorkMessage(ctx context.Context, arg CreateWorkMessageParams) (CreateWorkMessageRow, error) {
	row := q.db.QueryRow(ctx, createWorkMessage,
		arg.MessageID,
		arg.WorkID,
		arg.AuthorUserID,
		arg.Text,
		arg.InputSeq,
		arg.IdempotencyKey,
		arg.RequestDigest,
	)
	var i CreateWorkMessageRow
	err := row.Scan(
		&i.MessageID,
		&i.WorkID,
		&i.AuthorUserID,
		&i.Text,
		&i.InputSeq,
		&i.CreatedAt,
	)
	return i, err
}

const findWorkByCreateIdempotency = `-- name: FindWorkByCreateIdempotency :one
SELECT work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id,
    created_at, create_request_digest
FROM works
WHERE
    space_id = $1
    AND creator_user_id = $2
    AND create_idempotency_key = $3
`

type FindWorkByCreateIdempotencyParams struct {
	SpaceID              string
	CreatorUserID        string
	CreateIdempotencyKey string
}

type FindWorkByCreateIdempotencyRow struct {
	WorkID              string
	SpaceID             string
	Goal                string
	Lifecycle           string
	OwnerUserID         string
	CreatorUserID       string
	CreatedAt           pgtype.Timestamptz
	CreateRequestDigest []byte
}

func (q *Queries) FindWorkByCreateIdempotency(ctx context.Context, arg FindWorkByCreateIdempotencyParams) (FindWorkByCreateIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findWorkByCreateIdempotency, arg.SpaceID, arg.CreatorUserID, arg.CreateIdempotencyKey)
	var i FindWorkByCreateIdempotencyRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.CreatorUserID,
		&i.CreatedAt,
		&i.CreateRequestDigest,
	)
	return i, err
}

const findWorkMessageByIdempotency = `-- name: FindWorkMessageByIdempotency :one
SELECT message_id, work_id, author_user_id, text, input_seq, created_at, request_digest
FROM work_messages
WHERE
    work_id = $1
    AND author_user_id = $2
    AND idempotency_key = $3
`

type FindWorkMessageByIdempotencyParams struct {
	WorkID         string
	AuthorUserID   string
	IdempotencyKey string
}

type FindWorkMessageByIdempotencyRow struct {
	MessageID     string
	WorkID        string
	AuthorUserID  string
	Text          string
	InputSeq      int64
	CreatedAt     pgtype.Timestamptz
	RequestDigest []byte
}

func (q *Queries) FindWorkMessageByIdempotency(ctx context.Context, arg FindWorkMessageByIdempotencyParams) (FindWorkMessageByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findWorkMessageByIdempotency, arg.WorkID, arg.AuthorUserID, arg.IdempotencyKey)
	var i FindWorkMessageByIdempotencyRow
	err := row.Scan(
		&i.MessageID,
		&i.WorkID,
		&i.AuthorUserID,
		&i.Text,
		&i.InputSeq,
		&i.CreatedAt,
		&i.RequestDigest,
	)
	return i, err
}

const listWorkMessages = `-- name: ListWorkMessages :many
SELECT message_id, work_id, author_user_id, text, input_seq, created_at
FROM work_messages
WHERE work_id = $1
ORDER BY input_seq ASC
`

type ListWorkMessagesRow struct {
	MessageID    string
	WorkID       string
	AuthorUserID string
	Text         string
	InputSeq     int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListWorkMessages(ctx context.Context, workID string) ([]ListWorkMessagesRow, error) {
	rows, err := q.db.Query(ctx, listWorkMessages, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkMessagesRow
	for rows.Next() {
		var i ListWorkMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.WorkID,
			&i.AuthorUserID,
			&i.Text,
			&i.InputSeq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorks = `-- name: ListWorks :many
SELECT work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id,
    input_head_seq, applied_input_seq, understanding_version, understanding, next_step, created_at
FROM works
WHERE space_id = $1
ORDER BY created_at DESC, work_id DESC
`

type ListWorksRow struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Lifecycle            string
	OwnerUserID          string
	CreatorUserID        string
	InputHeadSeq         int64
	AppliedInputSeq      int64
	UnderstandingVersion int64
	Understanding        *string
	NextStep             *string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ListWorks(ctx context.Context, spaceID string) ([]ListWorksRow, error) {
	rows, err := q.db.Query(ctx, listWorks, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorksRow
	for rows.Next() {
		var i ListWorksRow
		if err := rows.Scan(
			&i.WorkID,
			&i.SpaceID,
			&i.Goal,
			&i.Lifecycle,
			&i.OwnerUserID,
			&i.CreatorUserID,
			&i.InputHeadSeq,
			&i.AppliedInputSeq,
			&i.UnderstandingVersion,
			&i.Understanding,
			&i.NextStep,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadWork = `-- name: LoadWork :one
SELECT work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id,
    input_head_seq, applied_input_seq, understanding_version, understanding, next_step, created_at
FROM works
WHERE space_id = $1 AND work_id = $2
FOR SHARE
`

type LoadWorkParams struct {
	SpaceID string
	WorkID  string
}

type LoadWorkRow struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Lifecycle            string
	OwnerUserID          string
	CreatorUserID        string
	InputHeadSeq         int64
	AppliedInputSeq      int64
	UnderstandingVersion int64
	Understanding        *string
	NextStep             *string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) LoadWork(ctx context.Context, arg LoadWorkParams) (LoadWorkRow, error) {
	row := q.db.QueryRow(ctx, loadWork, arg.SpaceID, arg.WorkID)
	var i LoadWorkRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.CreatorUserID,
		&i.InputHeadSeq,
		&i.AppliedInputSeq,
		&i.UnderstandingVersion,
		&i.Understanding,
		&i.NextStep,
		&i.CreatedAt,
	)
	return i, err
}

const lockActiveWorkMembership = `-- name: LockActiveWorkMembership :one
SELECT version
FROM space_memberships
WHERE
    space_id = $1
    AND user_id = $2
    AND revoked_at IS NULL
FOR SHARE
`

type LockActiveWorkMembershipParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) LockActiveWorkMembership(ctx context.Context, arg LockActiveWorkMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockActiveWorkMembership, arg.SpaceID, arg.UserID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockWork = `-- name: LockWork :one
SELECT work_id, space_id, goal, lifecycle, owner_user_id, creator_user_id,
    input_head_seq, applied_input_seq, understanding_version, understanding, next_step, created_at
FROM works
WHERE space_id = $1 AND work_id = $2
FOR UPDATE
`

type LockWorkParams struct {
	SpaceID string
	WorkID  string
}

type LockWorkRow struct {
	WorkID               string
	SpaceID              string
	Goal                 string
	Lifecycle            string
	OwnerUserID          string
	CreatorUserID        string
	InputHeadSeq         int64
	AppliedInputSeq      int64
	UnderstandingVersion int64
	Understanding        *string
	NextStep             *string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) LockWork(ctx context.Context, arg LockWorkParams) (LockWorkRow, error) {
	row := q.db.QueryRow(ctx, lockWork, arg.SpaceID, arg.WorkID)
	var i LockWorkRow
	err := row.Scan(
		&i.WorkID,
		&i.SpaceID,
		&i.Goal,
		&i.Lifecycle,
		&i.OwnerUserID,
		&i.CreatorUserID,
		&i.InputHeadSeq,
		&i.AppliedInputSeq,
		&i.UnderstandingVersion,
		&i.Understanding,
		&i.NextStep,
		&i.CreatedAt,
	)
	return i, err
}
